// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func testOptions() options {
	o := defaultOptions()
	o.now = func() time.Time { return time.Date(2026, 10, 1, 12, 0, 0, 0, time.UTC) }
	return o
}

// NTF1-D01: make notifications порождает SendInvite и эталон структуры;
// поля структуры — атрибуты с типами из notification.yaml.
func TestNTF1D01_GeneratesTypedSendFunction(t *testing.T) {
	tr := newTree(t)
	tr.generate()
	src := tr.read("svc/notifications_invite.gen.go")
	require.True(t, strings.HasPrefix(src, "// Code generated by notifygen. DO NOT EDIT."))

	f, err := parser.ParseFile(token.NewFileSet(), "gen.go", src, 0)
	require.NoError(t, err)
	require.Equal(t, "svc", f.Name.Name)
	fields := map[string]string{}
	var send *ast.FuncDecl
	ast.Inspect(f, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.TypeSpec:
			if x.Name.Name == "InviteAttrs" {
				for _, fl := range x.Type.(*ast.StructType).Fields.List {
					for _, nm := range fl.Names {
						fields[nm.Name] = types(fl.Type)
					}
				}
			}
		case *ast.FuncDecl:
			if x.Name.Name == "SendInvite" {
				send = x
			}
		}
		return true
	})
	require.Equal(t, map[string]string{"To": "string", "Initiator": "string", "InviterName": "string", "Token": "string"}, fields)
	require.NotNil(t, send)
	require.Len(t, send.Type.Params.List, 3)
	require.Equal(t, "context.Context", types(send.Type.Params.List[0].Type))
	require.Equal(t, "pgx.Tx", types(send.Type.Params.List[1].Type))
	require.Equal(t, "InviteAttrs", types(send.Type.Params.List[2].Type))

	require.Contains(t, tr.read("svc/notifications/invite/revision.yaml"), "revision: 1\n")
}

func types(e ast.Expr) string {
	switch x := e.(type) {
	case *ast.Ident:
		return x.Name
	case *ast.SelectorExpr:
		return types(x.X) + "." + x.Sel.Name
	}
	return "?"
}

// NTF1-D01: порождённый файл собирается против corelib этого дерева —
// SendX действительно зовёт feed.Put с описанием feed.TemplateDesc.
func TestNTF1D01_GeneratedFileCompilesAgainstFeed(t *testing.T) {
	corelib, err := filepath.Abs("../..")
	require.NoError(t, err)
	tr := newTree(t)
	tr.write("svc/notifications/all/notification.yaml", allNotification)
	tr.write("svc/notifications/all/body.ru.yaml", allBody)
	tr.generate()
	tr.write("go.mod", "module example.invalid/src\n\ngo 1.26.0\n\nrequire github.com/PRO-Robotech/corelib v0.0.0\n\n"+
		"replace github.com/PRO-Robotech/corelib => "+corelib+"\n")
	sum, err := os.ReadFile(filepath.Join(corelib, "go.sum"))
	require.NoError(t, err)
	tr.write("go.sum", string(sum))
	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = tr.root
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod", "GOPROXY=off", "GOWORK=off")
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "сборка порождённого: %s", out)
}

const allNotification = `name: all
class: notice
ttl: 1h
limits:
  - {scope: recipient, window: 1h, max: 5}
  - {scope: recipient, window: 600s, max: 2}
  - {scope: recipient, window: 30m, max: 4}
  - {scope: recipient, window: 24h, max: 9}
  - {scope: recipient, window: 3600s, max: 3}
attributes:
  subject_name: {type: text, presence: required}
  note: {type: text, presence: optional}
  code: {type: secret, presence: required}
  target: {type: path, presence: required}
  issued_at: {type: timestamp, presence: required}
subject:
  ru: "{{ subject_name }}"
`

const allBody = `blocks:
  - heading: "Привет"
  - p: "{{ note }}"
    when: note
  - p: "{{ issued_at }}"
  - code: "{{ code }}"
  - button: {text: "Открыть", path: target}
`

// УК86 (а), УК77, УК83: лимиты описания упорядочены feed.LimitLess — по
// числу секунд (600 < 1800 < 3600 < 86400), повтор пары сведён к меньшему max;
// УК70: экспорт X<Scope>Per<Window>.
func TestUK86_LimitsAreOrderedBySecondsAndPairsReduced(t *testing.T) {
	tr := newTree(t)
	tr.write("svc/notifications/all/notification.yaml", allNotification)
	tr.write("svc/notifications/all/body.ru.yaml", allBody)
	tr.generate()
	src := tr.read("svc/notifications_all.gen.go")
	i600 := strings.Index(src, "WindowSeconds: 600,")
	i1800 := strings.Index(src, "WindowSeconds: 1800,")
	i3600 := strings.Index(src, "WindowSeconds: 3600,")
	i86400 := strings.Index(src, "WindowSeconds: 86400,")
	require.True(t, i600 >= 0 && i600 < i1800 && i1800 < i3600 && i3600 < i86400, "порядок по числу секунд")
	require.Equal(t, 1, strings.Count(src, "WindowSeconds: 3600,"), "повтор пары сведён в один")
	require.Contains(t, src, "WindowSeconds: 3600, Max: 3}", "сведён к меньшему max")
	for _, c := range []string{`AllRecipientPer10Minutes\s+= 2\n`, `AllRecipientPer30Minutes\s+= 4\n`, `AllRecipientPerHour\s+= 3\n`, `AllRecipientPerDay\s+= 9\n`} {
		require.Regexp(t, c, src)
	}
	inv := tr.read("svc/notifications_invite.gen.go")
	require.Regexp(t, `InviteRecipientPerDay\s+= 3\n`, inv)
	require.Regexp(t, `InviteInitiatorPerHour\s+= 20\n`, inv)
	// timestamp — time.Time; optional — через form.Presence
	require.Regexp(t, `IssuedAt\s+time.Time\n`, src)
}

// УК58: тело SendX не несёт литерала сравнения по виду и сравнения поля с
// нулём — решение «задано ли» принимает form.Presence (проба разбора).
func TestUK58_SendXCarriesNoKindComparison(t *testing.T) {
	tr := newTree(t)
	tr.write("svc/notifications/all/notification.yaml", allNotification)
	tr.write("svc/notifications/all/body.ru.yaml", allBody)
	tr.generate()
	for _, file := range []string{"svc/notifications_all.gen.go", "svc/notifications_invite.gen.go"} {
		findings, cmps := kindComparisons(t, tr.read(file))
		t.Logf("%s: сравнений осмотрено %d", file, cmps)
		require.Empty(t, findings, file)
	}
	// инъекция: сравнение поля с пустой строкой — находка
	findings, _ := kindComparisons(t, "package p\nfunc f(a struct{ Note string }) bool { return a.Note == \"\" }\n")
	require.Len(t, findings, 1)
	findings, _ = kindComparisons(t, "package p\nimport \"x/form\"\nfunc f(k form.Kind) bool { return k == form.KindText }\n")
	require.Len(t, findings, 1)
}

func kindComparisons(t *testing.T, src string) (findings []string, cmps int) {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "gen.go", src, 0)
	require.NoError(t, err)
	ast.Inspect(f, func(n ast.Node) bool {
		b, ok := n.(*ast.BinaryExpr)
		if !ok || (b.Op != token.EQL && b.Op != token.NEQ) {
			return true
		}
		cmps++
		for _, side := range []ast.Expr{b.X, b.Y} {
			switch x := side.(type) {
			case *ast.BasicLit:
				findings = append(findings, fset.Position(b.Pos()).String()+": сравнение с литералом")
			case *ast.SelectorExpr:
				if strings.HasPrefix(x.Sel.Name, "Kind") {
					findings = append(findings, fset.Position(b.Pos()).String()+": сравнение по виду")
				}
			case *ast.CompositeLit:
				findings = append(findings, fset.Position(b.Pos()).String()+": сравнение с составным литералом")
			}
		}
		return true
	})
	return findings, cmps
}

// NTF1-D01: -check -list печатает множество порождаемых файлов, равное
// множеству записанных генерацией в копию дерева без порождённых файлов, — в
// обе стороны.
func TestNTF1D01_ListEqualsWrittenSetBothWays(t *testing.T) {
	tr := newTree(t)
	tr.write("svc/notifications/all/notification.yaml", allNotification)
	tr.write("svc/notifications/all/body.ru.yaml", allBody)
	// рукописный файл с заголовком notifygen, которого генератор не порождает
	tr.write("svc/notifications_handmade.gen.go", "// Code generated by notifygen. DO NOT EDIT.\n\npackage svc\n")
	before := tr.files()
	tr.generate()
	after := tr.files()
	var written []string
	for p, c := range after {
		if b, ok := before[p]; !ok || b != c {
			written = append(written, p)
		}
	}
	sort.Strings(written)
	r := tr.run("-check", "-list")
	require.Equal(t, 0, r.code, r.stdout+r.stderr)
	got := listed(r.stdout)
	require.Empty(t, listDiff(written, got))
	require.Len(t, got, 4)
	require.NotContains(t, got, "svc/notifications_handmade.gen.go")
	require.Contains(t, got, "svc/notifications_invite.gen.go")
	require.True(t, slices.IsSorted(got))

	// инъекция: путь, которого генератор не пишет, — проба называет его
	injected := append(slices.Clone(got), "svc/notifications_ghost.gen.go")
	sort.Strings(injected)
	diff := listDiff(written, injected)
	require.Equal(t, []string{"лишний в -list: svc/notifications_ghost.gen.go"}, diff)
	diff = listDiff(written, got[1:])
	require.Equal(t, []string{"недостающий в -list: " + got[0]}, diff)
}

// NTF1-D01: дерево без каталогов notifications — вывод пуст, код 0.
func TestNTF1D01_EmptyTreeListsNothing(t *testing.T) {
	tr := &tree{t: t, root: t.TempDir()}
	tr.write("svc/svc.go", "package svc\n")
	r := tr.run("-check", "-list")
	require.Equal(t, 0, r.code, r.stderr)
	require.Empty(t, listed(r.stdout))
	require.Contains(t, r.stdout, "шаблонов 0")
}

// NTF1-D02: правка шаблона без перегенерации — красный -check с именем
// файла; -check -list — красный код и то же множество; после генерации —
// зелёный.
func TestNTF1D02_EditWithoutRegenerationIsRed(t *testing.T) {
	tr := newTree(t)
	tr.generate()
	green := tr.run("-check", "-list")
	require.Equal(t, 0, green.code)
	tr.edit("svc/notifications/invite/notification.yaml", "  token: {type: token, presence: required}\n",
		"  token: {type: token, presence: required}\n  inviter_email: {type: text, presence: required}\n")
	r := tr.run("-check")
	require.NotEqual(t, 0, r.code)
	require.Contains(t, r.stderr, "invite: набор атрибутов не равен отпечатку ревизии")
	require.Contains(t, r.stderr, "svc/notifications_invite.gen.go")
	rl := tr.run("-check", "-list")
	require.NotEqual(t, 0, rl.code)
	require.Equal(t, listed(green.stdout), listed(rl.stdout))
	tr.generate()
	require.Equal(t, 0, tr.run("-check").code)
}

// NTF1-D07 (-check): каталог без revision.yaml — «ревизия не порождена».
func TestNTF1D07_MissingRevisionIsRed(t *testing.T) {
	tr := newTree(t)
	r := tr.run("-check")
	require.NotEqual(t, 0, r.code)
	require.Contains(t, r.stderr, "invite: ревизия не порождена")
}

// NTF1-D07: ревизию ведёт генератор — растёт ровно со сменой набора.
func TestNTF1D07_RevisionGrowsExactlyWithTheSet(t *testing.T) {
	tr := newTree(t)
	rev := func() string { return tr.read("svc/notifications/invite/revision.yaml") }
	num := func() string {
		for _, l := range strings.Split(rev(), "\n") {
			if strings.HasPrefix(l, "revision: ") {
				return strings.TrimPrefix(l, "revision: ")
			}
		}
		return ""
	}
	notif := "svc/notifications/invite/notification.yaml"
	steps := []struct {
		name string
		do   func()
		want string
		same bool
	}{
		{"(1) исходный каталог", func() {}, "1", false},
		{"(2) текст блока и ttl", func() {
			tr.edit("svc/notifications/invite/body.ru.yaml", "приглашает вас в облако.", "зовёт вас.")
			tr.edit(notif, "ttl: 168h", "ttl: 72h")
		}, "1", true},
		{"(3) атрибут inviter_email", func() {
			tr.edit(notif, "  token: {type: token, presence: required}\n",
				"  token: {type: token, presence: required}\n  inviter_email: {type: text, presence: required}\n")
			tr.edit("svc/notifications/invite/body.ru.yaml", "  - heading: \"Вас пригласили\"\n",
				"  - heading: \"Вас пригласили\"\n  - p: \"{{ inviter_email }}\"\n")
		}, "2", false},
		{"(4) тип inviter_email — secret", func() {
			tr.edit(notif, "inviter_email: {type: text,", "inviter_email: {type: secret,")
			tr.edit("svc/notifications/invite/body.ru.yaml", "  - p: \"{{ inviter_email }}\"\n", "  - code: \"{{ inviter_email }}\"\n")
		}, "3", false},
		{"(5) inviter_name в теме", func() {
			tr.edit(notif, `ru: "Приглашение в облако"`, `ru: "Приглашение от {{ inviter_name }}"`)
		}, "4", false},
		{"(6) класс notice", func() { tr.edit(notif, "class: security", "class: notice") }, "5", false},
		{"(7) inviter_email optional", func() {
			tr.edit(notif, "inviter_email: {type: secret, presence: required}", "inviter_email: {type: secret, presence: optional}")
			tr.edit("svc/notifications/invite/body.ru.yaml", "  - code: \"{{ inviter_email }}\"\n",
				"  - code: \"{{ inviter_email }}\"\n    when: inviter_email\n")
		}, "6", false},
		{"(8) limits и текст heading", func() {
			tr.edit(notif, "max: 3}", "max: 5}")
			tr.edit("svc/notifications/invite/body.ru.yaml", "Вас пригласили", "Приглашение")
		}, "6", true},
	}
	prev := ""
	for _, s := range steps {
		s.do()
		tr.generate()
		require.Equal(t, s.want, num(), s.name)
		if s.same {
			require.Equal(t, prev, rev(), "%s: файл побайтово прежний", s.name)
		}
		prev = rev()
		require.Equal(t, 0, tr.run("-check").code, s.name)
	}
	require.Contains(t, tr.read("svc/notifications_invite.gen.go"), "SchemaRev: 6,", "эталон пишет ревизию из файла")
}

// NTF1-D06: -version печатает версию модуля corelib.
func TestNTF1D06_VersionNamesTheCorelibModule(t *testing.T) {
	tr := newTree(t)
	r := tr.run("-version")
	require.Equal(t, 0, r.code)
	require.Contains(t, r.stdout, "github.com/PRO-Robotech/corelib ")
}

// Без каталога-пакета Go генерация не угадывает имя пакета.
func TestOwnerWithoutGoPackageIsRefused(t *testing.T) {
	tr := &tree{t: t, root: t.TempDir()}
	tr.write("svc/notifications/invite/notification.yaml", inviteNotification)
	tr.write("svc/notifications/invite/body.ru.yaml", inviteBody)
	r := tr.run()
	require.NotEqual(t, 0, r.code)
	require.Contains(t, r.stderr, "svc: каталог источника без пакета Go")
	require.False(t, tr.exists("svc/notifications_invite.gen.go"))
}

// Невалидный шаблон — находки валидатора, генерация ничего не пишет.
func TestInvalidCatalogWritesNothing(t *testing.T) {
	tr := newTree(t)
	tr.edit("svc/notifications/invite/notification.yaml", "class: security", "class: bulk")
	before := tr.files()
	r := tr.run()
	require.NotEqual(t, 0, r.code)
	require.Equal(t, before, tr.files())
	require.True(t, maps.Equal(before, tr.files()))
}

type brokenWriter struct{}

func (brokenWriter) Write([]byte) (int, error) { return 0, os.ErrClosed }

// CX1-35: оборванный вывод -list — красный код, а не короткое множество при
// коде 0; близнец — исправный вывод.
func TestListWithABrokenOutputIsRed(t *testing.T) {
	tr := newTree(t)
	tr.generate()
	var errb strings.Builder
	code := run([]string{"-root", tr.root, "-list"}, brokenWriter{}, &errb, testOptions())
	require.Equal(t, exitRed, code)
	require.Contains(t, errb.String(), "запись вывода")
	require.Equal(t, exitGreen, tr.run("-list").code)
}
