// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"github.com/PRO-Robotech/corelib/notify/feed/schema"
)

func migrations(t *testing.T, tr *tree) []string {
	t.Helper()
	entries, err := os.ReadDir(tr.path("svc/migrations"))
	if os.IsNotExist(err) {
		return nil
	}
	require.NoError(t, err)
	var out []string
	for _, e := range entries {
		out = append(out, e.Name())
	}
	sort.Strings(out)
	return out
}

// NTF1-D03, УК87 (а): init пишет одну миграцию с меткой времени; повторный
// init — изменений 0; в миграции нет функций, процедур, триггеров.
func TestNTF1D03_InitWritesOnceAndIsIdempotent(t *testing.T) {
	tr := newTree(t)
	tr.generate()
	tr.write("svc/migrations/20260101000000_items.sql", "-- +goose Up\nSELECT 1;\n")
	r := tr.run("init", "-service", "svc", "-migrations", "svc/migrations")
	require.Equal(t, 0, r.code, r.stderr)
	got := migrations(t, tr)
	require.Equal(t, []string{"20260101000000_items.sql", "20261001120000_notification_feed_v1.sql"}, got)
	body := tr.read("svc/migrations/20261001120000_notification_feed_v1.sql")
	want, err := schema.Migration("svc", schema.V1)
	require.NoError(t, err)
	require.Equal(t, want, body)
	up := strings.ToUpper(body)
	for _, banned := range []string{"CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", "PROCEDURE", "TRIGGER"} {
		require.NotContains(t, up, banned)
	}

	before := tr.files()
	r = tr.run("init", "-service", "svc", "-migrations", "svc/migrations")
	require.Equal(t, 0, r.code, r.stderr)
	require.Contains(t, r.stdout, "изменений 0")
	require.Equal(t, before, tr.files())
	require.Equal(t, 0, tr.run("-check").code, "-check сверяет миграцию побайтово и зелёный")
}

// Метка новой миграции старше каждой применённой даже при отстающих часах:
// номер — наибольший из применённых плюс один.
func TestInitLabelOutranksEveryAppliedMigration(t *testing.T) {
	tr := newTree(t)
	tr.write("svc/migrations/20991231235959_future.sql", "-- +goose Up\nSELECT 1;\n")
	r := tr.run("init", "-service", "svc", "-migrations", "svc/migrations")
	require.Equal(t, 0, r.code, r.stderr)
	require.Equal(t, []string{"20991231235959_future.sql", "20991231235960_notification_feed_v1.sql"}, migrations(t, tr))
}

// fakeSchemas — выпущенные версии v1 и v2: пин corelib поднят до схемы v2.
type fakeSchemas struct{}

func (fakeSchemas) Versions() []schema.Version { return []schema.Version{schema.V1, 2} }
func (fakeSchemas) Current() schema.Version    { return 2 }
func (fakeSchemas) Migration(svc string, v schema.Version) (string, error) {
	if v == schema.V1 {
		return schema.Migration(svc, v)
	}
	return "", fmt.Errorf("v%d целиком не выпускается", v)
}

func (fakeSchemas) Upgrade(svc string, from, to schema.Version) (string, error) {
	if from == schema.V1 && to == 2 {
		return fmt.Sprintf("-- Code generated by notifygen init; DO NOT EDIT.\n"+schema.HeaderPrefix+" service=%s version=2 from=1\n\n-- +goose Up\nSELECT 2;\n\n-- +goose Down\nSELECT 1;\n", svc), nil
	}
	return "", fmt.Errorf("переход v%d→v%d не выпущен", from, to)
}

// NTF1-D04: смена версии схемы — новый файл v2_from_v1, применённый v1
// побайтово тот же; правка применённого файла — красный -check с именем
// файла; близнец без правки — зелёный.
func TestNTF1D04_SchemaVersionChangeWritesANewFile(t *testing.T) {
	tr := newTree(t)
	tr.generate()
	require.Equal(t, 0, tr.run("init", "-service", "svc", "-migrations", "svc/migrations").code)
	v1 := tr.read("svc/migrations/20261001120000_notification_feed_v1.sql")

	opts := testOptions()
	opts.schemas = fakeSchemas{}
	opts.now = func() time.Time { return time.Date(2026, 10, 2, 0, 0, 0, 0, time.UTC) }
	r := runWith(tr, opts, "init", "-service", "svc", "-migrations", "svc/migrations")
	require.Equal(t, 0, r.code, r.stderr)
	require.Equal(t, []string{"20261001120000_notification_feed_v1.sql", "20261002000000_notification_feed_v2_from_v1.sql"}, migrations(t, tr))
	require.Equal(t, v1, tr.read("svc/migrations/20261001120000_notification_feed_v1.sql"))
	require.Equal(t, 0, runWith(tr, opts, "-check").code, "близнец: v1 как выпущен, v2_from_v1 добавлен")

	tr.edit("svc/migrations/20261001120000_notification_feed_v1.sql", "count          integer", "count          bigint ")
	r = runWith(tr, opts, "-check")
	require.NotEqual(t, 0, r.code)
	require.Contains(t, r.stderr, "svc/migrations/20261001120000_notification_feed_v1.sql: применённый файл миграции ленты правлен")
	r = runWith(tr, opts, "-check", "-base", "HEAD")
	require.NotEqual(t, 0, r.code, "без git база не найдена — тоже красный")
}

func runWith(tr *tree, o options, args ...string) result {
	tr.t.Helper()
	var out, errb strings.Builder
	code := run(append([]string{"-root", tr.root}, args...), &out, &errb, o)
	return result{code: code, stdout: out.String(), stderr: errb.String()}
}
