// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"math"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/PRO-Robotech/corelib/notify/feed"
	"github.com/PRO-Robotech/corelib/notify/form"
	"github.com/PRO-Robotech/corelib/notify/spec"
)

// genHeader — первая строка порождённого файла.
const genHeader = "// Code generated by notifygen. DO NOT EDIT."

// goName — имя Go из слов через «-» или «_»: каждое слово с заглавной.
// Слова формата начинаются буквой, поэтому отображение взаимно однозначно.
func goName(s string) string {
	var b strings.Builder
	for _, w := range strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == '_' }) {
		b.WriteString(strings.ToUpper(w[:1]) + w[1:])
	}
	return b.String()
}

// windowName — длина окна словом имени константы: Day, 2Days, Hour,
// 30Minutes, 45Seconds.
func windowName(sec int32) string {
	unit := func(n int32, one, many string) string {
		if n == 1 {
			return one
		}
		return strconv.Itoa(int(n)) + many
	}
	switch {
	case sec%86400 == 0:
		return unit(sec/86400, "Day", "Days")
	case sec%3600 == 0:
		return unit(sec/3600, "Hour", "Hours")
	case sec%60 == 0:
		return unit(sec/60, "Minute", "Minutes")
	}
	return unit(sec, "Second", "Seconds")
}

// descLimits — лимиты описания: по feed.LimitLess (scope побайтно, окно
// числом секунд — УК86 (а)); повтор пары (scope, window_seconds) сведён к
// меньшему max — письмо, прошедшее меньший, проходит и больший (УК77, УК83).
func descLimits(t spec.Template) ([]feed.Limit, error) {
	var out []feed.Limit
	for i, l := range t.Limits {
		sec := l.Window / time.Second
		if l.Window%time.Second != 0 || sec <= 0 || sec > math.MaxInt32 {
			return nil, fmt.Errorf("%s: limits[%d]: окно вне целых секунд int32", t.Name, i)
		}
		if l.Max < 1 || l.Max > math.MaxInt32 {
			return nil, fmt.Errorf("%s: limits[%d]: max вне [1..int32]", t.Name, i)
		}
		out = append(out, feed.Limit{Scope: feed.Scope(l.Scope), WindowSeconds: int32(sec), Max: int32(l.Max)})
	}
	sort.SliceStable(out, func(i, j int) bool { return feed.LimitLess(out[i], out[j]) })
	reduced := out[:0]
	for _, l := range out {
		if n := len(reduced); n > 0 && !feed.LimitLess(reduced[n-1], l) {
			reduced[n-1].Max = min(reduced[n-1].Max, l.Max)
			continue
		}
		reduced = append(reduced, l)
	}
	return reduced, nil
}

func kindIdent(k form.Kind) (string, error) {
	switch k {
	case form.KindText:
		return "form.KindText", nil
	case form.KindSecret:
		return "form.KindSecret", nil
	case form.KindPath:
		return "form.KindPath", nil
	case form.KindToken:
		return "form.KindToken", nil
	case form.KindTimestamp:
		return "form.KindTimestamp", nil
	}
	return "", fmt.Errorf("вид атрибута %q вне перечня form", string(k))
}

func classIdent(c spec.Class) (string, error) {
	switch c {
	case spec.ClassSecurity:
		return "feed.ClassSecurity", nil
	case spec.ClassNotice:
		return "feed.ClassNotice", nil
	}
	return "", fmt.Errorf("класс %q вне перечня", string(c))
}

func scopeIdent(s feed.Scope) string {
	if s == feed.ScopeInitiator {
		return "feed.ScopeInitiator"
	}
	return "feed.ScopeRecipient"
}

// render порождает notifications_<name>.gen.go шаблона t с ревизией rev в
// пакете pkg (З5).
func render(pkg string, t spec.Template, rev int) ([]byte, error) {
	limits, err := descLimits(t)
	if err != nil {
		return nil, err
	}
	class, err := classIdent(t.Class)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", t.Name, err)
	}
	name := goName(t.Name)
	desc := strings.ToLower(name[:1]) + name[1:] + "Desc"
	initiator := false
	for _, l := range limits {
		initiator = initiator || l.Scope == feed.ScopeInitiator
	}

	var b bytes.Buffer
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	p("%s\n// Шаблон %s, ревизия %d.\n\npackage %s\n\n", genHeader, t.Name, rev, pkg)
	p("import (\n\t\"context\"\n\t\"time\"\n\n\t\"github.com/jackc/pgx/v5\"\n\n")
	p("\t\"github.com/PRO-Robotech/corelib/notify/feed\"\n")
	if len(t.Attrs) > 0 {
		p("\t\"github.com/PRO-Robotech/corelib/notify/form\"\n")
	}
	p(")\n\n")

	if len(limits) > 0 {
		p("// Границы лимитов шаблона %s (экспорт для стражей вызывающего, УК70).\nconst (\n", t.Name)
		for _, l := range limits {
			p("\t%s%sPer%s = %d\n", name, goName(string(l.Scope)), windowName(l.WindowSeconds), l.Max)
		}
		p(")\n\n")
	}

	p("// %sAttrs — атрибуты шаблона %s. Нулевое поле optional — «не задан».\n", name, t.Name)
	p("type %sAttrs struct {\n\tTo string\n", name)
	if initiator {
		p("\tInitiator string\n")
	}
	for _, a := range t.Attrs {
		typ := "string"
		if a.Kind == form.KindTimestamp {
			typ = "time.Time"
		}
		p("\t%s %s\n", goName(a.Name), typ)
	}
	p("}\n\n")

	p("var %s = feed.TemplateDesc{\n\tName: %q,\n\tClass: %s,\n\tSchemaRev: %d,\n", desc, t.Name, class, rev)
	p("\tTTL: %d * time.Second,\n", int64(t.TTL/time.Second))
	p("\tLimits: []feed.Limit{\n")
	for _, l := range limits {
		p("\t\t{Scope: %s, WindowSeconds: %d, Max: %d},\n", scopeIdent(l.Scope), l.WindowSeconds, l.Max)
	}
	p("\t},\n\tAttrs: []feed.AttrDesc{\n")
	for _, a := range t.Attrs {
		kind, err := kindIdent(a.Kind)
		if err != nil {
			return nil, fmt.Errorf("%s: атрибут %s: %w", t.Name, a.Name, err)
		}
		presence := "feed.PresenceRequired"
		if a.Presence == spec.PresenceOptional {
			presence = "feed.PresenceOptional"
		}
		p("\t\t{Name: %q, Kind: %s, Presence: %s, Subject: %t},\n", a.Name, kind, presence, a.Subject)
	}
	p("\t},\n}\n\n")

	p("// Send%s ставит письмо шаблона %s в транзакции tx (feed.Put).\n", name, t.Name)
	p("func Send%s(ctx context.Context, tx pgx.Tx, a %sAttrs) error {\n", name, name)
	if initiator {
		p("\tvalues := feed.Values{Initiator: a.Initiator, Attrs: make(map[string]any, %d)}\n", len(t.Attrs))
	} else {
		p("\tvalues := feed.Values{Attrs: make(map[string]any, %d)}\n", len(t.Attrs))
	}
	for _, a := range t.Attrs {
		kind, _ := kindIdent(a.Kind)
		field := goName(a.Name)
		if a.Presence == spec.PresenceOptional {
			// «Не задан» решает form.Presence; значение вне формы уходит в Put,
			// и тот отвергает его сторожем с именем атрибута.
			p("\tif _, present, err := form.Presence(%s, a.%s); err != nil || present == form.Given {\n", kind, field)
			p("\t\tvalues.Attrs[%q] = a.%s\n\t}\n", a.Name, field)
			continue
		}
		p("\tvalues.Attrs[%q] = a.%s\n", a.Name, field)
	}
	p("\treturn feed.Put(ctx, tx, %s, a.To, values)\n}\n", desc)

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("%s: порождённый код не разбирается: %w", t.Name, err)
	}
	return out, nil
}
