// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: corelib/operation/operation_service.proto

package operationv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Operation resource to return.
	OperationId   string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_corelib_operation_operation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_operation_operation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_corelib_operation_operation_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type CancelOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the operation to cancel.
	OperationId   string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_corelib_operation_operation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_operation_operation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationRequest.ProtoReflect.Descriptor instead.
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return file_corelib_operation_operation_service_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

var File_corelib_operation_operation_service_proto protoreflect.FileDescriptor

const file_corelib_operation_operation_service_proto_rawDesc = "" +
	"\n" +
	")corelib/operation/operation_service.proto\x12\x11corelib.operation\x1a\x1cgoogle/api/annotations.proto\x1a!corelib/operation/operation.proto\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\";\n" +
	"\x16CancelOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId2\x84\x02\n" +
	"\x10OperationService\x12o\n" +
	"\x03Get\x12&.corelib.operation.GetOperationRequest\x1a\x1c.corelib.operation.Operation\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/operations/{operation_id}\x12\x7f\n" +
	"\x06Cancel\x12).corelib.operation.CancelOperationRequest\x1a\x1c.corelib.operation.Operation\",\x82\xd3\xe4\x93\x02&:\x01*\"!/operations/{operation_id}:cancelBCZAgithub.com/PRO-Robotech/corelib/api/corelib/operation;operationv1b\x06proto3"

var (
	file_corelib_operation_operation_service_proto_rawDescOnce sync.Once
	file_corelib_operation_operation_service_proto_rawDescData []byte
)

func file_corelib_operation_operation_service_proto_rawDescGZIP() []byte {
	file_corelib_operation_operation_service_proto_rawDescOnce.Do(func() {
		file_corelib_operation_operation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corelib_operation_operation_service_proto_rawDesc), len(file_corelib_operation_operation_service_proto_rawDesc)))
	})
	return file_corelib_operation_operation_service_proto_rawDescData
}

var file_corelib_operation_operation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_corelib_operation_operation_service_proto_goTypes = []any{
	(*GetOperationRequest)(nil),    // 0: corelib.operation.GetOperationRequest
	(*CancelOperationRequest)(nil), // 1: corelib.operation.CancelOperationRequest
	(*Operation)(nil),              // 2: corelib.operation.Operation
}
var file_corelib_operation_operation_service_proto_depIdxs = []int32{
	0, // 0: corelib.operation.OperationService.Get:input_type -> corelib.operation.GetOperationRequest
	1, // 1: corelib.operation.OperationService.Cancel:input_type -> corelib.operation.CancelOperationRequest
	2, // 2: corelib.operation.OperationService.Get:output_type -> corelib.operation.Operation
	2, // 3: corelib.operation.OperationService.Cancel:output_type -> corelib.operation.Operation
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_corelib_operation_operation_service_proto_init() }
func file_corelib_operation_operation_service_proto_init() {
	if File_corelib_operation_operation_service_proto != nil {
		return
	}
	file_corelib_operation_operation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corelib_operation_operation_service_proto_rawDesc), len(file_corelib_operation_operation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_corelib_operation_operation_service_proto_goTypes,
		DependencyIndexes: file_corelib_operation_operation_service_proto_depIdxs,
		MessageInfos:      file_corelib_operation_operation_service_proto_msgTypes,
	}.Build()
	File_corelib_operation_operation_service_proto = out.File
	file_corelib_operation_operation_service_proto_goTypes = nil
	file_corelib_operation_operation_service_proto_depIdxs = nil
}
