// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

package treehygiene_test

import (
	"strings"
	"testing"

	"github.com/PRO-Robotech/corelib/treehygiene"
)

const genHello = `// Code generated by notifygen; DO NOT EDIT.

package probe

import (
	"context"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
)

// SendProbeHello — порождённый вызов.
func SendProbeHello(ctx context.Context, tx pgx.Tx, to string) error {
	return feed.Put(ctx, tx, feed.TemplateDesc{}, to, feed.Values{})
}
`

const fixtureSourceTest = `
package probe

import (
	"context"
	"testing"

	"github.com/PRO-Robotech/corelib/notify/feed"
)

func TestFixture(t *testing.T) { _ = feed.Put(context.Background(), nil, feed.TemplateDesc{}, "", feed.Values{}) }
`

const probeMain = `
package main

import (
	"context"

	"example.invalid/kacho/services/notify/notifications/probe"
)

func main() { _ = probe.SendProbeHello(context.Background(), nil, "a@example.invalid") }
`

func feedPut(t *testing.T, root, list string) treehygiene.FeedPutReport {
	t.Helper()
	r, err := treehygiene.AuditFeedPutReferences(root, "pkg/api", []byte(list))
	if err != nil {
		t.Fatalf("гейт не исполнился: %v", err)
	}
	t.Logf("%s\n%s", r, kindsOf(r.Findings))
	return r
}

const helloList = "file services/notify/notifications/probe/notifications_probe_hello.gen.go\nfile services/notify/notifications/probe-hello/revision.yaml\n"

func probeTree(t *testing.T, module string, extra map[string]string) string {
	t.Helper()
	files := map[string]string{
		"services/notify/notifications/probe/notifications_probe_hello.gen.go": genHello,
		"services/notify/notifications/probe/fixture_test.go":                  fixtureSourceTest,
		"services/notify/cmd/notify-probe/main.go":                             strings.Replace(probeMain, kachoModule, module, 1),
	}
	for k, v := range extra {
		files[k] = v
	}
	return goSynth(t, module, files)
}

// Близнец NTF1-B28 (гейт Put): notify-probe зовёт порождённый SendProbeHello,
// фикстура зовёт feed.Put из тестового файла — гейт молчит.
func TestNTF1B28PutGate_TwinIsSilent(t *testing.T) {
	r := feedPut(t, probeTree(t, kachoModule, nil), helloList)
	if len(r.Findings) != 0 {
		t.Fatalf("близнец дал находки:\n%s", kindsOf(r.Findings))
	}
	if r.GeneratorFiles != 1 || r.RefsInGenerated != 1 || r.RefsOutside != 0 {
		t.Fatalf("перепись: %s", r)
	}
}

// NTF1-B28 (гейт Put), инъекции (1)–(3).
func TestNTF1B28PutGate_InjectionsAreFound(t *testing.T) {
	for name, tc := range map[string]struct {
		module string
		extra  map[string]string
		file   string
	}{
		"(1) прямой вызов в notify-probe": {kachoModule, map[string]string{
			"services/notify/cmd/notify-probe/direct.go": `
package main

import (
	"context"

	"github.com/PRO-Robotech/corelib/notify/feed"
)

func direct() error { return feed.Put(context.Background(), nil, feed.TemplateDesc{}, "", feed.Values{}) }
`}, "services/notify/cmd/notify-probe/direct.go"},
		"(2) заголовок notifygen вне множества -list": {kachoModule, map[string]string{
			"services/notify/cmd/notify-probe/fake.gen.go": "// Code generated by notifygen; DO NOT EDIT.\n" + `
package main

import (
	"context"

	"github.com/PRO-Robotech/corelib/notify/feed"
)

func fake() error { return feed.Put(context.Background(), nil, feed.TemplateDesc{}, "", feed.Values{}) }
`}, "services/notify/cmd/notify-probe/fake.gen.go"},
		"(3) значение-функция в kaname": {"example.invalid/kaname", map[string]string{
			"internal/p/p.go": `
package p

import "github.com/PRO-Robotech/corelib/notify/feed"

// P — значение-функция.
var P = feed.Put
`}, "internal/p/p.go"},
	} {
		t.Run(name, func(t *testing.T) {
			r := feedPut(t, probeTree(t, tc.module, tc.extra), helloList)
			if len(r.Findings) != 1 || !strings.HasPrefix(r.Findings[0].Position, tc.file) {
				t.Fatalf("ожидалась одна находка в %s:\n%s", tc.file, kindsOf(r.Findings))
			}
		})
	}
}

// Вход -list: генератор, давший неразобранный вывод, — красный прогон гейта,
// а не пустое множество.
func TestNTF1B28PutGate_UnparsedListIsARefusal(t *testing.T) {
	root := probeTree(t, kachoModule, nil)
	for name, list := range map[string]string{
		"чужая строка":       helloList + "notifygen: шаблон не найден\n",
		"путь вне дерева":    "file ../x.gen.go\n",
		"пустая строка file": "file \n",
	} {
		if _, err := treehygiene.AuditFeedPutReferences(root, "pkg/api", []byte(list)); err == nil {
			t.Errorf("%s: вывод -list принят", name)
		}
	}
}

// УК63: StartSweeper под условием, читающим флаг, — находка; близнец —
// вызов вне условия.
func TestUK63_StartSweeperUnderTheFlagIsFound(t *testing.T) {
	const body = `
package main

import (
	"context"

	"github.com/PRO-Robotech/corelib/notify/feed"
)

func wire(ctx context.Context, en feed.Enabled, cfg feed.SweeperConfig) error {
	%s
	return nil
}
`
	under := strings.Replace(body, "%s", "if en.On() {\n\t\tif _, err := feed.StartSweeper(ctx, cfg); err != nil {\n\t\t\treturn err\n\t\t}\n\t}", 1)
	r := feedPut(t, probeTree(t, kachoModule, map[string]string{"services/notify/cmd/notify-probe/wire.go": under}), helloList)
	if len(r.Findings) != 1 || r.Findings[0].Kind != string(treehygiene.FeedSweeperUnderFlag) {
		t.Fatalf("StartSweeper под флагом не найден:\n%s", kindsOf(r.Findings))
	}
	free := strings.Replace(body, "%s", "if _, err := feed.StartSweeper(ctx, cfg); err != nil {\n\t\treturn err\n\t}\n\t_ = en.On()", 1)
	r = feedPut(t, probeTree(t, kachoModule, map[string]string{"services/notify/cmd/notify-probe/wire.go": free}), helloList)
	if len(r.Findings) != 0 || r.SweeperStarts != 1 {
		t.Fatalf("близнец: %s\n%s", r, kindsOf(r.Findings))
	}
}
