// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

package treehygiene_test

import (
	"strings"
	"testing"
)

// genHelloPutID — порождённый файл в форме, отвечающей id строки (feed.PutID).
const genHelloPutID = `// Code generated by notifygen; DO NOT EDIT.

package probe

import (
	"context"

	"github.com/jackc/pgx/v5"

	"github.com/PRO-Robotech/corelib/notify/feed"
)

// SendProbeHello — порождённый вызов.
func SendProbeHello(ctx context.Context, tx pgx.Tx, to string) (feed.Queued, error) {
	return feed.PutID(ctx, tx, feed.TemplateDesc{}, to, feed.Values{})
}
`

const probeMainPutID = `
package main

import (
	"context"

	"example.invalid/kacho/services/notify/notifications/probe"
)

func main() { _, _ = probe.SendProbeHello(context.Background(), nil, "a@example.invalid") }
`

func probeTreePutID(t *testing.T, extra map[string]string) string {
	t.Helper()
	files := map[string]string{
		"services/notify/notifications/probe/notifications_probe_hello.gen.go": genHelloPutID,
		"services/notify/cmd/notify-probe/main.go":                             probeMainPutID,
	}
	for k, v := range extra {
		files[k] = v
	}
	return goSynth(t, kachoModule, files)
}

// Близнец NTF1-B28 для PutID: ссылка на feed.PutID в порождённом файле —
// молчание, и она сосчитана ссылкой генератора.
func TestNTF1B28PutGate_PutIDInGeneratedIsSilent(t *testing.T) {
	r := feedPut(t, probeTreePutID(t, nil), helloList)
	if len(r.Findings) != 0 {
		t.Fatalf("близнец дал находки:\n%s", kindsOf(r.Findings))
	}
	if r.GeneratorFiles != 1 || r.RefsInGenerated != 1 || r.RefsOutside != 0 {
		t.Fatalf("перепись: %s", r)
	}
}

// NTF1-B28 для PutID: прямой вызов и значение-функция вне порождённых файлов —
// находки. Постановка, отвечающая id, — тот же глагол записи в ленту, и обход
// генератора через неё — тот же дефект, что через Put.
func TestNTF1B28PutGate_PutIDOutsideGeneratorIsFound(t *testing.T) {
	for name, tc := range map[string]struct {
		extra map[string]string
		file  string
	}{
		"прямой вызов PutID в notify-probe": {map[string]string{
			"services/notify/cmd/notify-probe/direct.go": `
package main

import (
	"context"

	"github.com/PRO-Robotech/corelib/notify/feed"
)

func direct() (feed.Queued, error) {
	return feed.PutID(context.Background(), nil, feed.TemplateDesc{}, "", feed.Values{})
}
`}, "services/notify/cmd/notify-probe/direct.go"},
		"значение-функция PutID": {map[string]string{
			"internal/p/p.go": `
package p

import "github.com/PRO-Robotech/corelib/notify/feed"

// P — значение-функция.
var P = feed.PutID
`}, "internal/p/p.go"},
	} {
		t.Run(name, func(t *testing.T) {
			r := feedPut(t, probeTreePutID(t, tc.extra), helloList)
			if len(r.Findings) != 1 || !strings.HasPrefix(r.Findings[0].Position, tc.file) {
				t.Fatalf("ожидалась одна находка в %s:\n%s", tc.file, kindsOf(r.Findings))
			}
			if !strings.Contains(r.Findings[0].Why, "feed.PutID") {
				t.Fatalf("находка не называет предмет feed.PutID: %q", r.Findings[0].Why)
			}
		})
	}
}
