// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

package treehygiene_test

import (
	"go/build"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"

	"github.com/PRO-Robotech/corelib/treehygiene"
)

const kachoModule = "example.invalid/kacho"

// setFirstString — вспомогательный пакет инъекции (1) NTF1-B28 (гейт): без
// импорта unsafe пишет строку в первое поле значения через reflect.
const setFirstString = `
package setstr

import "reflect"

// SetFirstString пишет s в первое поле *dst.
func SetFirstString(dst any, s string) {
	f := reflect.ValueOf(dst).Elem().Field(0)
	reflect.NewAt(f.Type(), f.Addr().UnsafePointer()).Elem().SetString(s)
}
`

const linkBuilder = `
package link

import (
	"example.invalid/kacho/internal/setstr"

	"github.com/PRO-Robotech/corelib/notify/form"
)

// Build — сборщик ссылки.
func Build() (string, error) {
	var p form.Path
	setstr.SetFirstString(&p, "//evil")
	return p.Value()
}
`

const twinLinkBuilder = `
package link

import "github.com/PRO-Robotech/corelib/notify/form"

// Build — сборщик ссылки.
func Build() (string, error) {
	p, err := form.ParsePath("/a")
	if err != nil {
		return "", err
	}
	return p.Value()
}
`

const generatedStub = `// Code generated by protoc-gen-go. DO NOT EDIT.

package api

import _ "unsafe"
`

func typeSafety(t *testing.T, root string) treehygiene.TypeSafetyReport {
	t.Helper()
	r, err := treehygiene.AuditTypeSafetyBypass(root, "pkg/api")
	if err != nil {
		t.Fatalf("гейт не исполнился: %v", err)
	}
	t.Logf("%s\n%s", r, kindsOf(r.Findings))
	return r
}

func requireFindings(t *testing.T, r treehygiene.TypeSafetyReport, want map[treehygiene.TypeSafetyKind]string) {
	t.Helper()
	got := map[treehygiene.TypeSafetyKind][]string{}
	for _, f := range r.Findings {
		got[treehygiene.TypeSafetyKind(f.Kind)] = append(got[treehygiene.TypeSafetyKind(f.Kind)], f.Position)
	}
	for k, file := range want {
		ps, ok := got[k]
		if !ok {
			t.Errorf("вида %s нет среди находок", k)
			continue
		}
		if !strings.HasPrefix(ps[0], file) {
			t.Errorf("вид %s: координата %v, ожидалась в %s", k, ps, file)
		}
	}
	if len(got) != len(want) {
		t.Errorf("видов находок %d, ожидалось %d", len(got), len(want))
	}
}

// Близнец NTF1-B28 (гейт): стабы каталога стабов импортируют unsafe и
// печатаются пропущенными; сборщик ссылки получает form.Path из ParsePath —
// гейт молчит, виды (5)–(7) — 0.
func TestNTF1B28Gate_TwinIsSilentAndPrintsTheCensus(t *testing.T) {
	r := typeSafety(t, goSynth(t, kachoModule, map[string]string{
		"pkg/api/x.pb.go":           generatedStub,
		"services/notify/link/l.go": twinLinkBuilder,
	}))
	if len(r.Findings) != 0 {
		t.Fatalf("близнец дал находки:\n%s", kindsOf(r.Findings))
	}
	if r.Census.Generated != 1 {
		t.Fatalf("пропущено сгенерированных %d, ожидался 1", r.Census.Generated)
	}
	if len(r.Kinds) != 7 {
		t.Fatalf("видов в переписи %d, ожидалось 7", len(r.Kinds))
	}
	for _, k := range treehygiene.TypeSafetyKinds() {
		if r.Kinds[k] != 0 {
			t.Fatalf("вид %s: %d узлов на близнеце", k, r.Kinds[k])
		}
	}
}

// NTF1-B28 (гейт), инъекции (1)–(4), (8): каждая — находка с координатой и
// видом.
func TestNTF1B28Gate_InjectionsAreFound(t *testing.T) {
	t.Run("(1) NewAt и UnsafePointer во вспомогательном пакете", func(t *testing.T) {
		r := typeSafety(t, goSynth(t, kachoModule, map[string]string{
			"internal/setstr/s.go":      setFirstString,
			"services/notify/link/l.go": linkBuilder,
		}))
		requireFindings(t, r, map[treehygiene.TypeSafetyKind]string{
			treehygiene.KindReflectNewAt: "internal/setstr/s.go", treehygiene.KindUnsafePointer: "internal/setstr/s.go",
		})
	})
	t.Run("(2) unsafe.Pointer над UnsafeAddr", func(t *testing.T) {
		r := typeSafety(t, goSynth(t, kachoModule, map[string]string{
			"internal/setstr/s.go": `
package setstr

import (
	"reflect"
	"unsafe"
)

// SetFirstString пишет s в первое поле *dst.
func SetFirstString(dst any, s string) {
	f := reflect.ValueOf(dst).Elem().Field(0)
	*(*string)(unsafe.Pointer(f.UnsafeAddr())) = s
}
`,
		}))
		requireFindings(t, r, map[treehygiene.TypeSafetyKind]string{
			treehygiene.KindImportUnsafe: "internal/setstr/s.go", treehygiene.KindUnsafeAddr: "internal/setstr/s.go",
		})
	})
	t.Run("(3) unsafe над address.Normalized", func(t *testing.T) {
		r := typeSafety(t, goSynth(t, kachoModule, map[string]string{
			"notify/feed/f.go": `
package feed

import (
	"unsafe"

	"github.com/PRO-Robotech/corelib/notify/address"
)

// Forge кладёт сырую строку в нормализованный адрес.
func Forge(raw string) address.Normalized {
	var n address.Normalized
	*(*string)(unsafe.Pointer(&n)) = raw
	return n
}
`,
		}))
		requireFindings(t, r, map[treehygiene.TypeSafetyKind]string{treehygiene.KindImportUnsafe: "notify/feed/f.go"})
	})
	t.Run("(4) заголовок генератора вне каталога стабов", func(t *testing.T) {
		r := typeSafety(t, goSynth(t, kachoModule, map[string]string{
			"internal/gen/g.go": strings.Replace(generatedStub, "package api", "package gen", 1),
		}))
		requireFindings(t, r, map[treehygiene.TypeSafetyKind]string{treehygiene.KindImportUnsafe: "internal/gen/g.go"})
		if r.Census.Generated != 0 {
			t.Fatalf("рукописный файл вне каталога стабов засчитан сгенерированным")
		}
	})
	t.Run("(5) инъекция (1) в kaname", func(t *testing.T) {
		r := typeSafety(t, goSynth(t, "example.invalid/kaname", map[string]string{
			"internal/setstr/s.go": setFirstString,
		}))
		requireFindings(t, r, map[treehygiene.TypeSafetyKind]string{
			treehygiene.KindReflectNewAt: "internal/setstr/s.go", treehygiene.KindUnsafePointer: "internal/setstr/s.go",
		})
	})
	t.Run("(8) import C", func(t *testing.T) {
		r := typeSafety(t, goSynth(t, kachoModule, map[string]string{
			"internal/cgo/c.go": `
package cgo

// int one(void) { return 1; }
import "C"

// One зовёт функцию C.
func One() int { return int(C.one()) }
`,
		}))
		requireFindings(t, r, map[treehygiene.TypeSafetyKind]string{treehygiene.KindImportC: "internal/cgo/c.go"})
	})
}

const setStrDecl = `
package setstr

// SetStr пишет s в первое поле dst; тело — в ассемблере.
func SetStr(dst any, s string)
`

// NTF1-B28 (гейт), инъекции (6), (7), (9): функция без тела и файл не на Go —
// находки разбором без ограничений сборки; тело только для чужой архитектуры
// обход не сужает.
func TestNTF1B28Gate_BodylessFuncAndNonGoSource(t *testing.T) {
	other := "arm64"
	if runtime.GOARCH == "arm64" {
		other = "amd64"
	}
	for name, files := range map[string]map[string]string{
		"(6) тело в asm своей архитектуры": {
			"internal/setstr/s.go":                         setStrDecl,
			"internal/setstr/asm_" + runtime.GOARCH + ".s": "TEXT ·SetStr(SB),$0\n\tRET\n",
		},
		"(7) тело только в asm чужой архитектуры": {
			"internal/setstr/s.go":                setStrDecl,
			"internal/setstr/asm_" + other + ".s": "TEXT ·SetStr(SB),$0\n\tRET\n",
		},
	} {
		t.Run(name, func(t *testing.T) {
			r := typeSafety(t, goSynth(t, kachoModule, files))
			requireFindings(t, r, map[treehygiene.TypeSafetyKind]string{
				treehygiene.KindBodyless: "internal/setstr/s.go", treehygiene.KindNonGoSource: "internal/setstr/asm_",
			})
		})
	}
	t.Run("(9) kaname: объявление без тела и .s, зовущий feed.Put", func(t *testing.T) {
		r := typeSafety(t, goSynth(t, "example.invalid/kaname", map[string]string{
			"internal/sneak/s.go": `
package sneak

import _ "github.com/PRO-Robotech/corelib/notify/feed"

// Put — вызов feed.Put мимо ссылки на объект.
func Put()
`,
			"internal/sneak/put_" + runtime.GOARCH + ".s": "// Тело зовёт feed.Put по символу, мимо ссылки на объект.\nTEXT ·Put(SB),$0-0\n\tRET\n",
		}))
		requireFindings(t, r, map[treehygiene.TypeSafetyKind]string{
			treehygiene.KindBodyless: "internal/sneak/s.go", treehygiene.KindNonGoSource: "internal/sneak/put_",
		})
	})
	t.Run("каталог без .go с файлом не на Go (NoGoError)", func(t *testing.T) {
		r := typeSafety(t, goSynth(t, kachoModule, map[string]string{
			"internal/ok/ok.go": "package ok\n",
			"third/blob/x.syso": "binary",
		}))
		requireFindings(t, r, map[treehygiene.TypeSafetyKind]string{treehygiene.KindNonGoSource: "third/blob/x.syso"})
	})
}

// УК45, CX1-40 (а): перечень расширений вида (7) сверен с классификацией
// тулчейна в обе стороны. Каждое расширение перечня тулчейн относит к
// исходникам не на Go; каждое расширение, которое тулчейн так относит, есть
// в перечне.
func TestUK45_NonGoExtensionsMatchTheToolchainBothWays(t *testing.T) {
	exts := treehygiene.NonGoSourceExtensions()
	dir := t.TempDir()
	for _, e := range exts {
		if err := os.WriteFile(filepath.Join(dir, "f"+e), []byte("x\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	// Кандидаты тулчейна: что go/build знает как исходники иных языков.
	candidates := []string{".c", ".cc", ".cpp", ".cxx", ".m", ".h", ".hh", ".hpp", ".hxx",
		".f", ".F", ".for", ".f90", ".s", ".S", ".sx", ".swig", ".swigcxx", ".syso"}
	for _, e := range candidates {
		p := filepath.Join(dir, "cand"+e)
		if _, err := os.Stat(p); err == nil {
			continue
		}
		if err := os.WriteFile(p, []byte("x\n"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	ctx := build.Default
	ctx.UseAllFiles = true
	ctx.CgoEnabled = true
	pkg, err := ctx.ImportDir(dir, 0)
	if err != nil {
		if _, ok := err.(*build.NoGoError); !ok {
			t.Fatalf("тулчейн не классифицировал каталог: %v", err)
		}
	}
	classified := map[string]bool{}
	for _, list := range [][]string{pkg.CFiles, pkg.CXXFiles, pkg.MFiles, pkg.HFiles, pkg.FFiles, pkg.SFiles,
		pkg.SwigFiles, pkg.SwigCXXFiles, pkg.SysoFiles, pkg.IgnoredOtherFiles} {
		for _, f := range list {
			classified[filepath.Ext(f)] = true
		}
	}
	for _, e := range exts {
		if !classified[e] {
			t.Errorf("расширение %s перечня тулчейн не относит к исходникам не на Go", e)
		}
	}
	for e := range classified {
		if !slices.Contains(exts, e) {
			t.Errorf("тулчейн связывает %s, а перечень вида (7) его не знает", e)
		}
	}
	t.Logf("расширений перечня %d, классифицировано тулчейном %d", len(exts), len(classified))
}

// Перечни объявлены однажды (УК44): изменение возвращённого среза не меняет
// следующего ответа.
func TestNotifyGateListsAreCopies(t *testing.T) {
	a := treehygiene.NonGoSourceExtensions()
	a[0] = "мусор"
	if treehygiene.NonGoSourceExtensions()[0] == "мусор" {
		t.Fatal("перечень расширений отдан по ссылке — вызывающий переопределил его")
	}
	k := treehygiene.TypeSafetyKinds()
	k[0] = "мусор"
	if treehygiene.TypeSafetyKinds()[0] == "мусор" {
		t.Fatal("перечень видов отдан по ссылке")
	}
}

// Прогон по corelib: версия модуля, числа видов, ноль находок.
func TestNTF1B28Gate_OnCorelib(t *testing.T) {
	r, err := treehygiene.AuditTypeSafetyBypass(corelibRoot(t), "api")
	if err != nil {
		t.Fatalf("гейт не исполнился: %v", err)
	}
	t.Logf("%s", r)
	if len(r.Findings) != 0 {
		t.Fatalf("находки по corelib:\n%s", kindsOf(r.Findings))
	}
	if r.Census.Generated == 0 {
		t.Fatal("стабы каталога api не пропущены ни разу — каталог стабов назван не тот")
	}
}
