// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: corelib/notify/feed.proto

package notifyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalNotificationFeedService_Claim_FullMethodName = "/corelib.notify.InternalNotificationFeedService/Claim"
	InternalNotificationFeedService_Ack_FullMethodName   = "/corelib.notify.InternalNotificationFeedService/Ack"
)

// InternalNotificationFeedServiceClient is the client API for InternalNotificationFeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalNotificationFeedService — сервер ленты модуля-источника.
//
// # Только внутренний слушатель
//
// Префикс `Internal` выводит службу из внешнего маршрутизатора механически, и
// `google.api.http` у методов не объявлен: ленту забирает служба по
// проверенному сертификату, а не клиент.
//
// # Объект проверки прав — лента, к которой привязан сервер
//
// Идентификатора ленты в запросах нет намеренно. Сервер поднимает модуль, и
// отдаёт он строки только своей ленты; объект проверки —
// `notification_feed:<модуль>`, значение которого сервер объявляет при подъёме
// (`bound_to_server`). Вызывающий назвать чужую ленту не может: ему нечем.
type InternalNotificationFeedServiceClient interface {
	// Claim — арендовать пачку строк, готовых к отправке.
	//
	// Выдаёт строки, чей срок не истёк, чья отсрочка прошла и у которых нет
	// действующей аренды, в порядке постановки. Каждая выданная строка получает
	// новый токен аренды; до конца аренды другой `Claim` её не выдаёт.
	//
	// Границы входа проверяются до первого обращения к базе и не усекаются:
	// `max` вне `[1..500]` и пустой `classes` — `INVALID_ARGUMENT` с именем поля.
	Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
	// Ack — записать исход арендованной строки.
	//
	// Исход записывается только действующей арендой. Повтор того же вызова
	// (тот же токен, тот же исход) после записанного исхода — успех без изменения
	// строки: ответ мог потеряться в сети после коммита. Тот же токен с другим
	// исходом — `FAILED_PRECONDITION` (`OUTCOME_ALREADY_RECORDED`); прочие случаи
	// утраченной аренды — `FAILED_PRECONDITION` (`LEASE_LOST`).
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
}

type internalNotificationFeedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalNotificationFeedServiceClient(cc grpc.ClientConnInterface) InternalNotificationFeedServiceClient {
	return &internalNotificationFeedServiceClient{cc}
}

func (c *internalNotificationFeedServiceClient) Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResponse)
	err := c.cc.Invoke(ctx, InternalNotificationFeedService_Claim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalNotificationFeedServiceClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, InternalNotificationFeedService_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalNotificationFeedServiceServer is the server API for InternalNotificationFeedService service.
// All implementations must embed UnimplementedInternalNotificationFeedServiceServer
// for forward compatibility.
//
// InternalNotificationFeedService — сервер ленты модуля-источника.
//
// # Только внутренний слушатель
//
// Префикс `Internal` выводит службу из внешнего маршрутизатора механически, и
// `google.api.http` у методов не объявлен: ленту забирает служба по
// проверенному сертификату, а не клиент.
//
// # Объект проверки прав — лента, к которой привязан сервер
//
// Идентификатора ленты в запросах нет намеренно. Сервер поднимает модуль, и
// отдаёт он строки только своей ленты; объект проверки —
// `notification_feed:<модуль>`, значение которого сервер объявляет при подъёме
// (`bound_to_server`). Вызывающий назвать чужую ленту не может: ему нечем.
type InternalNotificationFeedServiceServer interface {
	// Claim — арендовать пачку строк, готовых к отправке.
	//
	// Выдаёт строки, чей срок не истёк, чья отсрочка прошла и у которых нет
	// действующей аренды, в порядке постановки. Каждая выданная строка получает
	// новый токен аренды; до конца аренды другой `Claim` её не выдаёт.
	//
	// Границы входа проверяются до первого обращения к базе и не усекаются:
	// `max` вне `[1..500]` и пустой `classes` — `INVALID_ARGUMENT` с именем поля.
	Claim(context.Context, *ClaimRequest) (*ClaimResponse, error)
	// Ack — записать исход арендованной строки.
	//
	// Исход записывается только действующей арендой. Повтор того же вызова
	// (тот же токен, тот же исход) после записанного исхода — успех без изменения
	// строки: ответ мог потеряться в сети после коммита. Тот же токен с другим
	// исходом — `FAILED_PRECONDITION` (`OUTCOME_ALREADY_RECORDED`); прочие случаи
	// утраченной аренды — `FAILED_PRECONDITION` (`LEASE_LOST`).
	Ack(context.Context, *AckRequest) (*AckResponse, error)
	mustEmbedUnimplementedInternalNotificationFeedServiceServer()
}

// UnimplementedInternalNotificationFeedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalNotificationFeedServiceServer struct{}

func (UnimplementedInternalNotificationFeedServiceServer) Claim(context.Context, *ClaimRequest) (*ClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Claim not implemented")
}
func (UnimplementedInternalNotificationFeedServiceServer) Ack(context.Context, *AckRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedInternalNotificationFeedServiceServer) mustEmbedUnimplementedInternalNotificationFeedServiceServer() {
}
func (UnimplementedInternalNotificationFeedServiceServer) testEmbeddedByValue() {}

// UnsafeInternalNotificationFeedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalNotificationFeedServiceServer will
// result in compilation errors.
type UnsafeInternalNotificationFeedServiceServer interface {
	mustEmbedUnimplementedInternalNotificationFeedServiceServer()
}

func RegisterInternalNotificationFeedServiceServer(s grpc.ServiceRegistrar, srv InternalNotificationFeedServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalNotificationFeedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalNotificationFeedService_ServiceDesc, srv)
}

func _InternalNotificationFeedService_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalNotificationFeedServiceServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalNotificationFeedService_Claim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalNotificationFeedServiceServer).Claim(ctx, req.(*ClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalNotificationFeedService_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalNotificationFeedServiceServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalNotificationFeedService_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalNotificationFeedServiceServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalNotificationFeedService_ServiceDesc is the grpc.ServiceDesc for InternalNotificationFeedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalNotificationFeedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "corelib.notify.InternalNotificationFeedService",
	HandlerType: (*InternalNotificationFeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Claim",
			Handler:    _InternalNotificationFeedService_Claim_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _InternalNotificationFeedService_Ack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "corelib/notify/feed.proto",
}
