// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: corelib/notify/feed.proto

package notifyv1

import (
	_ "github.com/PRO-Robotech/corelib/api/corelib/authz/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationClass — класс письма. Отбирает строки в `Claim`; исход строки по
// классу решает сборка службы отправки, а не эта колонка.
type NotificationClass int32

const (
	NotificationClass_NOTIFICATION_CLASS_UNSPECIFIED NotificationClass = 0
	// SECURITY — извещения безопасности учётной записи.
	NotificationClass_SECURITY NotificationClass = 1
	// NOTICE — прочие служебные извещения.
	NotificationClass_NOTICE NotificationClass = 2
)

// Enum value maps for NotificationClass.
var (
	NotificationClass_name = map[int32]string{
		0: "NOTIFICATION_CLASS_UNSPECIFIED",
		1: "SECURITY",
		2: "NOTICE",
	}
	NotificationClass_value = map[string]int32{
		"NOTIFICATION_CLASS_UNSPECIFIED": 0,
		"SECURITY":                       1,
		"NOTICE":                         2,
	}
)

func (x NotificationClass) Enum() *NotificationClass {
	p := new(NotificationClass)
	*p = x
	return p
}

func (x NotificationClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationClass) Descriptor() protoreflect.EnumDescriptor {
	return file_corelib_notify_feed_proto_enumTypes[0].Descriptor()
}

func (NotificationClass) Type() protoreflect.EnumType {
	return &file_corelib_notify_feed_proto_enumTypes[0]
}

func (x NotificationClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationClass.Descriptor instead.
func (NotificationClass) EnumDescriptor() ([]byte, []int) {
	return file_corelib_notify_feed_proto_rawDescGZIP(), []int{0}
}

// OutcomeKind — вид исхода строки. Словарь закрыт.
type OutcomeKind int32

const (
	// OUTCOME_UNSPECIFIED — исход не назван; `Ack` отвечает `outcome: required`.
	OutcomeKind_OUTCOME_UNSPECIFIED OutcomeKind = 0
	// SENT — ретранслятор принял письмо. Терминален.
	OutcomeKind_SENT OutcomeKind = 1
	// RECIPIENT_REJECTED — ретранслятор отверг адресата. Терминален.
	OutcomeKind_RECIPIENT_REJECTED OutcomeKind = 2
	// DEFER — отложить; строка остаётся в ленте до `defer_for` и срока строки.
	OutcomeKind_DEFER OutcomeKind = 3
	// DENIED — права на отправку отозваны. Терминален.
	OutcomeKind_DENIED OutcomeKind = 4
	// INVALID — строка не может быть отправлена никогда. Терминален.
	OutcomeKind_INVALID OutcomeKind = 5
	// DROPPED — письмо сброшено ограничением на адресата. Терминален.
	OutcomeKind_DROPPED OutcomeKind = 6
	// EXPIRED — срок строки истёк. Ставит только уборщик источника; в `Ack` —
	// `INVALID_ARGUMENT`.
	OutcomeKind_EXPIRED OutcomeKind = 7
)

// Enum value maps for OutcomeKind.
var (
	OutcomeKind_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "SENT",
		2: "RECIPIENT_REJECTED",
		3: "DEFER",
		4: "DENIED",
		5: "INVALID",
		6: "DROPPED",
		7: "EXPIRED",
	}
	OutcomeKind_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"SENT":                1,
		"RECIPIENT_REJECTED":  2,
		"DEFER":               3,
		"DENIED":              4,
		"INVALID":             5,
		"DROPPED":             6,
		"EXPIRED":             7,
	}
)

func (x OutcomeKind) Enum() *OutcomeKind {
	p := new(OutcomeKind)
	*p = x
	return p
}

func (x OutcomeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutcomeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_corelib_notify_feed_proto_enumTypes[1].Descriptor()
}

func (OutcomeKind) Type() protoreflect.EnumType {
	return &file_corelib_notify_feed_proto_enumTypes[1]
}

func (x OutcomeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutcomeKind.Descriptor instead.
func (OutcomeKind) EnumDescriptor() ([]byte, []int) {
	return file_corelib_notify_feed_proto_rawDescGZIP(), []int{1}
}

// OutcomeReason — причина исхода. Словарь закрыт, корзины «прочее» нет.
//
// Какие причины допустимы при каком виде, решает одна таблица сочетаний на
// стороне сервера ленты; сочетание вне неё — `INVALID_ARGUMENT`. `SENT` и
// `RECIPIENT_REJECTED` причины не несут.
type OutcomeReason int32

const (
	OutcomeReason_OUTCOME_REASON_UNSPECIFIED OutcomeReason = 0
	// PLATFORM_UNAVAILABLE — платформа не смогла отправить (ретранслятор, служба
	// доступа, настройка). Вид `DEFER`; у `EXPIRED` — причина последней отсрочки.
	OutcomeReason_PLATFORM_UNAVAILABLE OutcomeReason = 1
	// GRANT_SKEW — права на отправку ещё нет. Вид `DEFER`; у `EXPIRED` — как выше.
	OutcomeReason_GRANT_SKEW OutcomeReason = 2
	// TEMPLATE_SKEW — шаблона нет в сборке службы отправки либо ревизия строки не
	// равна ревизии сборки. Вид `DEFER`; у `EXPIRED` — как выше.
	OutcomeReason_TEMPLATE_SKEW OutcomeReason = 3
	// RECIPIENT_NET — исчерпано ограничение на адресата. Вид `DEFER` или
	// `DROPPED`; у `EXPIRED` — как выше.
	OutcomeReason_RECIPIENT_NET OutcomeReason = 4
	// REVOKED — права на отправку отозваны. Вид `DENIED`.
	OutcomeReason_REVOKED OutcomeReason = 5
	// ATTRS_INVALID — атрибуты не по схеме шаблона. Вид `INVALID`.
	OutcomeReason_ATTRS_INVALID OutcomeReason = 6
	// CLASS_MISMATCH — класс строки не равен классу шаблона той же ревизии в
	// сборке. Вид `INVALID`.
	OutcomeReason_CLASS_MISMATCH OutcomeReason = 7
	// RECIPIENT_INVALID — адрес не разбирается. Вид `INVALID`.
	OutcomeReason_RECIPIENT_INVALID OutcomeReason = 8
	// CLASS_NOT_ALLOWED — класс не разрешён пространству. Вид `INVALID`.
	OutcomeReason_CLASS_NOT_ALLOWED OutcomeReason = 9
	// RECIPIENT_FORM_NOT_ALLOWED — форма адресата не разрешена пространству.
	// Вид `INVALID`.
	OutcomeReason_RECIPIENT_FORM_NOT_ALLOWED OutcomeReason = 10
	// SEALED_MISMATCH — шифротекст секрета не открывается ключом. Вид `INVALID`;
	// ставит сервер ленты.
	OutcomeReason_SEALED_MISMATCH OutcomeReason = 11
	// KEY_UNAVAILABLE — ключа секрета нет в кольце. Вид `INVALID`; ставит сервер
	// ленты.
	OutcomeReason_KEY_UNAVAILABLE OutcomeReason = 12
	// UNCLAIMED — строку не выдал ни один `Claim`. Только у `EXPIRED`.
	OutcomeReason_UNCLAIMED OutcomeReason = 13
	// NO_ACK — строка выдана, исход не записан. Только у `EXPIRED`.
	OutcomeReason_NO_ACK OutcomeReason = 14
)

// Enum value maps for OutcomeReason.
var (
	OutcomeReason_name = map[int32]string{
		0:  "OUTCOME_REASON_UNSPECIFIED",
		1:  "PLATFORM_UNAVAILABLE",
		2:  "GRANT_SKEW",
		3:  "TEMPLATE_SKEW",
		4:  "RECIPIENT_NET",
		5:  "REVOKED",
		6:  "ATTRS_INVALID",
		7:  "CLASS_MISMATCH",
		8:  "RECIPIENT_INVALID",
		9:  "CLASS_NOT_ALLOWED",
		10: "RECIPIENT_FORM_NOT_ALLOWED",
		11: "SEALED_MISMATCH",
		12: "KEY_UNAVAILABLE",
		13: "UNCLAIMED",
		14: "NO_ACK",
	}
	OutcomeReason_value = map[string]int32{
		"OUTCOME_REASON_UNSPECIFIED": 0,
		"PLATFORM_UNAVAILABLE":       1,
		"GRANT_SKEW":                 2,
		"TEMPLATE_SKEW":              3,
		"RECIPIENT_NET":              4,
		"REVOKED":                    5,
		"ATTRS_INVALID":              6,
		"CLASS_MISMATCH":             7,
		"RECIPIENT_INVALID":          8,
		"CLASS_NOT_ALLOWED":          9,
		"RECIPIENT_FORM_NOT_ALLOWED": 10,
		"SEALED_MISMATCH":            11,
		"KEY_UNAVAILABLE":            12,
		"UNCLAIMED":                  13,
		"NO_ACK":                     14,
	}
)

func (x OutcomeReason) Enum() *OutcomeReason {
	p := new(OutcomeReason)
	*p = x
	return p
}

func (x OutcomeReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutcomeReason) Descriptor() protoreflect.EnumDescriptor {
	return file_corelib_notify_feed_proto_enumTypes[2].Descriptor()
}

func (OutcomeReason) Type() protoreflect.EnumType {
	return &file_corelib_notify_feed_proto_enumTypes[2]
}

func (x OutcomeReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutcomeReason.Descriptor instead.
func (OutcomeReason) EnumDescriptor() ([]byte, []int) {
	return file_corelib_notify_feed_proto_rawDescGZIP(), []int{2}
}

type ClaimRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max — сколько строк выдать не больше чем; `[1..500]`. `0` — `max: required`,
	// больше 500 — `max: must be ≤ 500`; значение не усекается.
	Max uint32 `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	// classes — какие классы выдавать; набор, порядок не значим, повтор
	// значения ничего не меняет. Пустой — `classes: required`;
	// `NOTIFICATION_CLASS_UNSPECIFIED` в наборе — `INVALID_ARGUMENT` с именем поля.
	Classes       []NotificationClass `protobuf:"varint,2,rep,packed,name=classes,proto3,enum=corelib.notify.NotificationClass" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_corelib_notify_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_notify_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_corelib_notify_feed_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimRequest) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *ClaimRequest) GetClasses() []NotificationClass {
	if x != nil {
		return x.Classes
	}
	return nil
}

type ClaimResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// notifications — арендованные строки в порядке постановки (момент
	// постановки, затем `id`). Пустой список — строк, готовых к отправке, нет.
	Notifications []*ClaimedNotification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_corelib_notify_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_notify_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_corelib_notify_feed_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimResponse) GetNotifications() []*ClaimedNotification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

// ClaimedNotification — строка ленты под арендой вызывающего.
//
// Моментов по часам источника, которые получатель сравнивал бы со своими
// часами, здесь нет, кроме `enqueued_at`, который получатель ни с чем своим не
// сравнивает: остатки аренды и срока приходят длительностями, посчитанными
// часами источника.
type ClaimedNotification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id — идентификатор строки ленты (`ntf-…`).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// lease_token — токен этой аренды (UUID). Предъявляется в `Ack`.
	LeaseToken string `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	// lease_remaining — остаток аренды на момент ответа: разность, посчитанная
	// часами базы источника, минус время, прошедшее в процессе источника до
	// ответа. После него строка может быть выдана снова.
	LeaseRemaining *durationpb.Duration `protobuf:"bytes,3,opt,name=lease_remaining,json=leaseRemaining,proto3" json:"lease_remaining,omitempty"`
	// template — имя шаблона письма в пространстве модуля-источника.
	Template string `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	// schema_rev — ревизия шаблона, по которой строка поставлена.
	SchemaRev uint32 `protobuf:"varint,5,opt,name=schema_rev,json=schemaRev,proto3" json:"schema_rev,omitempty"`
	// class — класс строки.
	Class NotificationClass `protobuf:"varint,6,opt,name=class,proto3,enum=corelib.notify.NotificationClass" json:"class,omitempty"`
	// recipient — адресат. Форма «адрес» — единственная в этой редакции;
	// ветвление объявлено, чтобы следующая форма адресата не меняла смысл
	// существующего поля.
	//
	// Types that are valid to be assigned to Recipient:
	//
	//	*ClaimedNotification_Address
	Recipient isClaimedNotification_Recipient `protobuf_oneof:"recipient"`
	// attrs — значения атрибутов шаблона. Ключа нет — атрибут не задан; пустое
	// значение при присутствующем ключе — значение, а не отсутствие. Значения
	// секретных атрибутов приходят открытым текстом: источник расшифровывает их
	// перед ответом, а в покое хранит шифротекстом. Порядок ключей не значим.
	Attrs map[string]string `protobuf:"bytes,8,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// enqueued_at — момент постановки строки с ПОЛНОЙ точностью базы источника.
	// Не усекается до секунды: это внутренний контракт работы, а не ресурс, и
	// правило усечения моментов ресурса к нему не применяется. Получатель
	// передаёт его в решение о правах на отправку и ни с чем своим не сравнивает.
	EnqueuedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	// expires_in — остаток срока строки на момент ответа, той же формы, что
	// `lease_remaining`. Строка, срок которой истёк, в ответ не попадает.
	ExpiresIn     *durationpb.Duration `protobuf:"bytes,10,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimedNotification) Reset() {
	*x = ClaimedNotification{}
	mi := &file_corelib_notify_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimedNotification) ProtoMessage() {}

func (x *ClaimedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_notify_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimedNotification.ProtoReflect.Descriptor instead.
func (*ClaimedNotification) Descriptor() ([]byte, []int) {
	return file_corelib_notify_feed_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimedNotification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClaimedNotification) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *ClaimedNotification) GetLeaseRemaining() *durationpb.Duration {
	if x != nil {
		return x.LeaseRemaining
	}
	return nil
}

func (x *ClaimedNotification) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *ClaimedNotification) GetSchemaRev() uint32 {
	if x != nil {
		return x.SchemaRev
	}
	return 0
}

func (x *ClaimedNotification) GetClass() NotificationClass {
	if x != nil {
		return x.Class
	}
	return NotificationClass_NOTIFICATION_CLASS_UNSPECIFIED
}

func (x *ClaimedNotification) GetRecipient() isClaimedNotification_Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *ClaimedNotification) GetAddress() string {
	if x != nil {
		if x, ok := x.Recipient.(*ClaimedNotification_Address); ok {
			return x.Address
		}
	}
	return ""
}

func (x *ClaimedNotification) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *ClaimedNotification) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

func (x *ClaimedNotification) GetExpiresIn() *durationpb.Duration {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

type isClaimedNotification_Recipient interface {
	isClaimedNotification_Recipient()
}

type ClaimedNotification_Address struct {
	// address — адрес почты, как его поставил источник.
	Address string `protobuf:"bytes,7,opt,name=address,proto3,oneof"`
}

func (*ClaimedNotification_Address) isClaimedNotification_Recipient() {}

// Outcome — исход строки: вид и причина. Равенство исходов — равенство пары.
type Outcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          OutcomeKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=corelib.notify.OutcomeKind" json:"kind,omitempty"`
	Reason        OutcomeReason          `protobuf:"varint,2,opt,name=reason,proto3,enum=corelib.notify.OutcomeReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_corelib_notify_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_notify_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_corelib_notify_feed_proto_rawDescGZIP(), []int{3}
}

func (x *Outcome) GetKind() OutcomeKind {
	if x != nil {
		return x.Kind
	}
	return OutcomeKind_OUTCOME_UNSPECIFIED
}

func (x *Outcome) GetReason() OutcomeReason {
	if x != nil {
		return x.Reason
	}
	return OutcomeReason_OUTCOME_REASON_UNSPECIFIED
}

type AckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id — идентификатор строки (`ntf-…`). Не по форме —
	// `invalid notification id '<X>'`; неизвестный — `NOT_FOUND`.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// lease_token — токен аренды из `Claim`. Пустой или не UUID —
	// `INVALID_ARGUMENT` с именем поля до обращения к базе.
	LeaseToken string `protobuf:"bytes,2,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	// outcome — исход. Не задан или `OUTCOME_UNSPECIFIED` — `outcome: required`.
	Outcome *Outcome `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// defer_for — через сколько строку можно выдать снова. Обязателен при виде
	// `DEFER` и лежит в границах, объявленных сервером ленты; при ином виде
	// заданное поле — `INVALID_ARGUMENT` с именем `defer_for`, а не молча
	// проигнорированное. В равенство исходов не входит.
	DeferFor      *durationpb.Duration `protobuf:"bytes,4,opt,name=defer_for,json=deferFor,proto3" json:"defer_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_corelib_notify_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_notify_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_corelib_notify_feed_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AckRequest) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *AckRequest) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *AckRequest) GetDeferFor() *durationpb.Duration {
	if x != nil {
		return x.DeferFor
	}
	return nil
}

// AckResponse — исход записан (либо был записан тем же вызовом раньше).
type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_corelib_notify_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_corelib_notify_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_corelib_notify_feed_proto_rawDescGZIP(), []int{5}
}

var File_corelib_notify_feed_proto protoreflect.FileDescriptor

const file_corelib_notify_feed_proto_rawDesc = "" +
	"\n" +
	"\x19corelib/notify/feed.proto\x12\x0ecorelib.notify\x1a$corelib/authz/v1/authz_options.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\fClaimRequest\x12\x10\n" +
	"\x03max\x18\x01 \x01(\rR\x03max\x12;\n" +
	"\aclasses\x18\x02 \x03(\x0e2!.corelib.notify.NotificationClassR\aclasses\"Z\n" +
	"\rClaimResponse\x12I\n" +
	"\rnotifications\x18\x01 \x03(\v2#.corelib.notify.ClaimedNotificationR\rnotifications\"\x9e\x04\n" +
	"\x13ClaimedNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\tR\n" +
	"leaseToken\x12B\n" +
	"\x0flease_remaining\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0eleaseRemaining\x12\x1a\n" +
	"\btemplate\x18\x04 \x01(\tR\btemplate\x12\x1d\n" +
	"\n" +
	"schema_rev\x18\x05 \x01(\rR\tschemaRev\x127\n" +
	"\x05class\x18\x06 \x01(\x0e2!.corelib.notify.NotificationClassR\x05class\x12\x1a\n" +
	"\aaddress\x18\a \x01(\tH\x00R\aaddress\x12D\n" +
	"\x05attrs\x18\b \x03(\v2..corelib.notify.ClaimedNotification.AttrsEntryR\x05attrs\x12;\n" +
	"\venqueued_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\x128\n" +
	"\n" +
	"expires_in\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\texpiresIn\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\trecipient\"q\n" +
	"\aOutcome\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.corelib.notify.OutcomeKindR\x04kind\x125\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1d.corelib.notify.OutcomeReasonR\x06reason\"\xa8\x01\n" +
	"\n" +
	"AckRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vlease_token\x18\x02 \x01(\tR\n" +
	"leaseToken\x121\n" +
	"\aoutcome\x18\x03 \x01(\v2\x17.corelib.notify.OutcomeR\aoutcome\x126\n" +
	"\tdefer_for\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bdeferFor\"\r\n" +
	"\vAckResponse*Q\n" +
	"\x11NotificationClass\x12\"\n" +
	"\x1eNOTIFICATION_CLASS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSECURITY\x10\x01\x12\n" +
	"\n" +
	"\x06NOTICE\x10\x02*\x86\x01\n" +
	"\vOutcomeKind\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04SENT\x10\x01\x12\x16\n" +
	"\x12RECIPIENT_REJECTED\x10\x02\x12\t\n" +
	"\x05DEFER\x10\x03\x12\n" +
	"\n" +
	"\x06DENIED\x10\x04\x12\v\n" +
	"\aINVALID\x10\x05\x12\v\n" +
	"\aDROPPED\x10\x06\x12\v\n" +
	"\aEXPIRED\x10\a*\xc6\x02\n" +
	"\rOutcomeReason\x12\x1e\n" +
	"\x1aOUTCOME_REASON_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PLATFORM_UNAVAILABLE\x10\x01\x12\x0e\n" +
	"\n" +
	"GRANT_SKEW\x10\x02\x12\x11\n" +
	"\rTEMPLATE_SKEW\x10\x03\x12\x11\n" +
	"\rRECIPIENT_NET\x10\x04\x12\v\n" +
	"\aREVOKED\x10\x05\x12\x11\n" +
	"\rATTRS_INVALID\x10\x06\x12\x12\n" +
	"\x0eCLASS_MISMATCH\x10\a\x12\x15\n" +
	"\x11RECIPIENT_INVALID\x10\b\x12\x15\n" +
	"\x11CLASS_NOT_ALLOWED\x10\t\x12\x1e\n" +
	"\x1aRECIPIENT_FORM_NOT_ALLOWED\x10\n" +
	"\x12\x13\n" +
	"\x0fSEALED_MISMATCH\x10\v\x12\x13\n" +
	"\x0fKEY_UNAVAILABLE\x10\f\x12\r\n" +
	"\tUNCLAIMED\x10\r\x12\n" +
	"\n" +
	"\x06NO_ACK\x10\x0e2\xc3\x02\n" +
	"\x1fInternalNotificationFeedService\x12\x92\x01\n" +
	"\x05Claim\x12\x1c.corelib.notify.ClaimRequest\x1a\x1d.corelib.notify.ClaimResponse\"L\x8a\xb5\x18 platform.notification_feed.claim\x92\xb5\x18\x06reader\x9a\xb5\x18\x15\n" +
	"\x11notification_feed \x01\xa2\xb5\x18\x011\x12\x8a\x01\n" +
	"\x03Ack\x12\x1a.corelib.notify.AckRequest\x1a\x1b.corelib.notify.AckResponse\"J\x8a\xb5\x18\x1eplatform.notification_feed.ack\x92\xb5\x18\x06reader\x9a\xb5\x18\x15\n" +
	"\x11notification_feed \x01\xa2\xb5\x18\x011B=Z;github.com/PRO-Robotech/corelib/api/corelib/notify;notifyv1b\x06proto3"

var (
	file_corelib_notify_feed_proto_rawDescOnce sync.Once
	file_corelib_notify_feed_proto_rawDescData []byte
)

func file_corelib_notify_feed_proto_rawDescGZIP() []byte {
	file_corelib_notify_feed_proto_rawDescOnce.Do(func() {
		file_corelib_notify_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_corelib_notify_feed_proto_rawDesc), len(file_corelib_notify_feed_proto_rawDesc)))
	})
	return file_corelib_notify_feed_proto_rawDescData
}

var file_corelib_notify_feed_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_corelib_notify_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_corelib_notify_feed_proto_goTypes = []any{
	(NotificationClass)(0),        // 0: corelib.notify.NotificationClass
	(OutcomeKind)(0),              // 1: corelib.notify.OutcomeKind
	(OutcomeReason)(0),            // 2: corelib.notify.OutcomeReason
	(*ClaimRequest)(nil),          // 3: corelib.notify.ClaimRequest
	(*ClaimResponse)(nil),         // 4: corelib.notify.ClaimResponse
	(*ClaimedNotification)(nil),   // 5: corelib.notify.ClaimedNotification
	(*Outcome)(nil),               // 6: corelib.notify.Outcome
	(*AckRequest)(nil),            // 7: corelib.notify.AckRequest
	(*AckResponse)(nil),           // 8: corelib.notify.AckResponse
	nil,                           // 9: corelib.notify.ClaimedNotification.AttrsEntry
	(*durationpb.Duration)(nil),   // 10: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_corelib_notify_feed_proto_depIdxs = []int32{
	0,  // 0: corelib.notify.ClaimRequest.classes:type_name -> corelib.notify.NotificationClass
	5,  // 1: corelib.notify.ClaimResponse.notifications:type_name -> corelib.notify.ClaimedNotification
	10, // 2: corelib.notify.ClaimedNotification.lease_remaining:type_name -> google.protobuf.Duration
	0,  // 3: corelib.notify.ClaimedNotification.class:type_name -> corelib.notify.NotificationClass
	9,  // 4: corelib.notify.ClaimedNotification.attrs:type_name -> corelib.notify.ClaimedNotification.AttrsEntry
	11, // 5: corelib.notify.ClaimedNotification.enqueued_at:type_name -> google.protobuf.Timestamp
	10, // 6: corelib.notify.ClaimedNotification.expires_in:type_name -> google.protobuf.Duration
	1,  // 7: corelib.notify.Outcome.kind:type_name -> corelib.notify.OutcomeKind
	2,  // 8: corelib.notify.Outcome.reason:type_name -> corelib.notify.OutcomeReason
	6,  // 9: corelib.notify.AckRequest.outcome:type_name -> corelib.notify.Outcome
	10, // 10: corelib.notify.AckRequest.defer_for:type_name -> google.protobuf.Duration
	3,  // 11: corelib.notify.InternalNotificationFeedService.Claim:input_type -> corelib.notify.ClaimRequest
	7,  // 12: corelib.notify.InternalNotificationFeedService.Ack:input_type -> corelib.notify.AckRequest
	4,  // 13: corelib.notify.InternalNotificationFeedService.Claim:output_type -> corelib.notify.ClaimResponse
	8,  // 14: corelib.notify.InternalNotificationFeedService.Ack:output_type -> corelib.notify.AckResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_corelib_notify_feed_proto_init() }
func file_corelib_notify_feed_proto_init() {
	if File_corelib_notify_feed_proto != nil {
		return
	}
	file_corelib_notify_feed_proto_msgTypes[2].OneofWrappers = []any{
		(*ClaimedNotification_Address)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_corelib_notify_feed_proto_rawDesc), len(file_corelib_notify_feed_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_corelib_notify_feed_proto_goTypes,
		DependencyIndexes: file_corelib_notify_feed_proto_depIdxs,
		EnumInfos:         file_corelib_notify_feed_proto_enumTypes,
		MessageInfos:      file_corelib_notify_feed_proto_msgTypes,
	}.Build()
	File_corelib_notify_feed_proto = out.File
	file_corelib_notify_feed_proto_goTypes = nil
	file_corelib_notify_feed_proto_depIdxs = nil
}
