// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

package spec

import (
	"bytes"
	"errors"
	"fmt"
	"regexp"
	"strconv"

	"gopkg.in/yaml.v3"
)

// revisionHeader — первая строка revision.yaml: файл порождает генератор.
const revisionHeader = "# Code generated by notifygen. DO NOT EDIT.\n"

// fingerprintRe — форма записанного отпечатка. Версия алгоритма — любая
// v<N>: база, записанная прежней версией, читается (решение «набор тот же»
// принимает пересчёт, а не эта строка).
var fingerprintRe = regexp.MustCompile(`^v[0-9]+:sha256:[0-9a-f]{64}$`)

// ErrRevision — revision.yaml вне формы.
var ErrRevision = errors.New("notify/spec: revision.yaml вне формы")

// WriteRevision — ЕДИНСТВЕННЫЙ писатель revision.yaml (CX1-45 (г)). Вывод
// детерминирован: при том же содержимом файл побайтово прежний (NTF1-D07).
func WriteRevision(r Revision) ([]byte, error) {
	if err := checkRevision(r); err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString(revisionHeader)
	b.WriteString("revision: " + strconv.Itoa(r.Number) + "\n")
	b.WriteString("fingerprint: " + r.Fingerprint + "\n")
	return b.Bytes(), nil
}

// ReadRevision — ЕДИНСТВЕННЫЙ читатель revision.yaml. Строгий: ключей два,
// ревизия — целое YAML ≥ 1, отпечаток — v<N>:sha256:<64 hex>.
func ReadRevision(data []byte) (Revision, error) {
	var root yaml.Node
	if err := yaml.Unmarshal(data, &root); err != nil {
		return Revision{}, fmt.Errorf("%w: %s", ErrRevision, RuleYAML)
	}
	r, fs := parseRevision(&root, "revision.yaml")
	if len(fs) > 0 {
		return Revision{}, fmt.Errorf("%w: %w", ErrRevision, fs)
	}
	return r, nil
}

func checkRevision(r Revision) error {
	if r.Number < 1 {
		return fmt.Errorf("%w: %s", ErrRevision, RuleRevision)
	}
	if !fingerprintRe.MatchString(r.Fingerprint) {
		return fmt.Errorf("%w: %s", ErrRevision, RuleFingerprintForm)
	}
	return nil
}

// parseRevision разбирает документ revision.yaml в находки валидатора.
func parseRevision(root *yaml.Node, file string) (Revision, Findings) {
	c := &collector{file: file}
	m := c.mapping(docNode(root), 0, "")
	if m == nil {
		return Revision{}, c.out
	}
	var r Revision
	fields := c.fields(m, "", 0, "revision", "fingerprint")
	if n, ok := fields["revision"]; !ok {
		c.add(m, 0, "revision", RuleRevision, "")
	} else if n.Kind != yaml.ScalarNode || n.Tag != "!!int" {
		c.add(n, 0, "revision", RuleRevision, "")
	} else if v, err := strconv.Atoi(n.Value); err != nil || v < 1 {
		c.add(n, 0, "revision", RuleRevision, "")
	} else {
		r.Number = v
	}
	if n, ok := fields["fingerprint"]; !ok {
		c.add(m, 0, "fingerprint", RuleFingerprintForm, "")
	} else if n.Kind != yaml.ScalarNode || n.Tag != "!!str" || !fingerprintRe.MatchString(n.Value) {
		c.add(n, 0, "fingerprint", RuleFingerprintForm, "")
	} else {
		r.Fingerprint = n.Value
	}
	return r, c.out
}
