// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

package resourceevent

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strconv"
	"strings"
	"text/template"
	"time"

	"github.com/PRO-Robotech/corelib/ids"
	"github.com/PRO-Robotech/corelib/notify/feed/internal/tablename"
	"github.com/PRO-Robotech/corelib/notify/spec"
	"github.com/PRO-Robotech/corelib/validate/nameform"
)

// fileHeader — первая строка миграции функции.
const fileHeader = "-- Code generated by notifygen init; DO NOT EDIT.\n"

// bodyMarker — начало определения функции в теле; за ним — отпечаток версии
// шаблона. По нему тело опознаётся и из него извлекаются входы.
const bodyMarker = "-- notifygen resource-event template: "

// crockford — алфавит тела id строки ленты (ids: Crockford base32,
// строчный). Что каждая буква алфавита — буква id каталога ids и наоборот,
// держит проба пакета.
const crockford = "0123456789abcdefghjkmnpqrstvwxyz"

// namePayloadKey — ключ имени в полезной нагрузке строки снятия
// (subscription.NamePayloadKey; равенство держит проба пакета).
const namePayloadKey = "name"

// v1Text — шаблон тела версии 1. Выпущенный текст не правится: смена
// шаблона — новая версия с новым отпечатком рядом с прежней, иначе тело,
// применённое у потребителя, перестанет выводиться из своей версии
// (TestReleasedVersionsAreFrozen).
//
// id строки ленты — приставка ntf и 17 букв Crockford из 17 случайных байт
// двух gen_random_uuid (байт 6 первого — номер версии UUID, он пропущен;
// младшие пять бит прочих байт равновероятны).
const v1Text = `-- notifygen resource-event template: {{.Version}}
-- schema_rev: {{.SchemaRev}}
-- ttl_seconds: {{.TTLSeconds}}
-- service: {{.Service}}
-- module: {{.Module}}
-- signal: {{.SignalObject}}
-- journal: {{.Table}}
-- columns: kind={{.C.Kind}} id={{.C.ID}} change={{.C.Change}} payload={{.C.Payload}} project={{.C.Project}} initiator={{.C.Initiator}} occurred_at={{.C.OccurredAt}}
-- signal_change: {{.SignalChange}}
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION {{.Function}}() RETURNS trigger
LANGUAGE plpgsql AS ${{.Function}}$
DECLARE
  v_flag      text := NULLIF(current_setting('kacho_feed.enabled', true), '');
  v_name_form text;
  v_scope     text;
  v_change    text;
  v_attrs     jsonb;
  v_name      text;
  v_rand      bytea;
  v_id        text := '{{.IDPrefix}}';
  v_i         integer;
BEGIN
  IF v_flag IS NULL THEN
    RAISE EXCEPTION 'resource-event: setting kacho_feed.enabled is not set in the transaction writing {{.Table}}';
  END IF;
  IF v_flag = 'false' THEN
    RETURN NULL;
  END IF;
  IF v_flag <> 'true' THEN
    RAISE EXCEPTION 'resource-event: setting kacho_feed.enabled is neither true nor false';
  END IF;
  SELECT k.name_form, k.scope INTO v_name_form, v_scope
    FROM (VALUES
{{.KindRows}}
    ) AS k (kind, name_form, scope)
   WHERE k.kind = NEW.{{.C.Kind}};
  IF NOT FOUND THEN
    RAISE EXCEPTION 'resource-event: kind % is outside the kind table of {{.Table}}', NEW.{{.C.Kind}};
  END IF;
  SELECT c.change INTO v_change
    FROM (VALUES
{{.ChangeRows}}
    ) AS c (word, change)
   WHERE c.word = NEW.{{.C.Change}};
  IF NOT FOUND THEN
    RAISE EXCEPTION 'resource-event: change % of kind % is outside the change table of {{.Table}}', NEW.{{.C.Change}}, NEW.{{.C.Kind}};
  END IF;
  IF v_scope = 'project' THEN
    IF NEW.{{.C.Project}} IS NULL OR NEW.{{.C.Project}} = '' THEN
      RAISE EXCEPTION 'resource-event: project kind % has no project anchor in {{.Table}}', NEW.{{.C.Kind}};
    END IF;
    v_scope := 'project:' || NEW.{{.C.Project}};
  END IF;
  IF NEW.{{.C.Initiator}} IS NULL OR NEW.{{.C.Initiator}} = '' THEN
    RAISE EXCEPTION 'resource-event: row of kind % in {{.Table}} has no initiator', NEW.{{.C.Kind}};
  END IF;
  v_attrs := jsonb_build_object(
    'kind', NEW.{{.C.Kind}},
    'resource_id', NEW.{{.C.ID}},
    'scope', v_scope,
    'change', v_change,
    'initiator', NEW.{{.C.Initiator}},
    'occurred_at', to_char(date_trunc('second', NEW.{{.C.OccurredAt}}) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
  IF v_change = 'DELETED' AND v_name_form = 'dns' THEN
    v_name := NEW.{{.C.Payload}} ->> '{{.NameKey}}';
    IF v_name ~ '{{.NameForm}}' THEN
      v_attrs := v_attrs || jsonb_build_object('name', v_name);
    END IF;
  END IF;
  v_rand := uuid_send(gen_random_uuid()) || uuid_send(gen_random_uuid());
  FOREACH v_i IN ARRAY ARRAY[0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17] LOOP
    v_id := v_id || substr('{{.Alphabet}}', get_byte(v_rand, v_i) % 32 + 1, 1);
  END LOOP;
  {{.InsertInto}}
    (id, template, schema_rev, class, recipient_address, attrs, secret_attrs, state, expires_at)
    VALUES (v_id, '{{.Template}}', {{.SchemaRev}}, '{{.Class}}', '', v_attrs, NULL, 'pending', now() + make_interval(secs => {{.TTLSeconds}}));
  INSERT INTO {{.Table}} ({{.C.Kind}}, {{.C.ID}}, {{.C.Change}}, {{.C.Payload}})
    VALUES ('{{.SignalKey}}', '{{.Module}}', '{{.SignalChange}}', '{}');
  RETURN NULL;
END;
${{.Function}}$;
-- +goose StatementEnd
`

// v1Attrs — атрибуты, которые ставит тело версии 1, по имени (Р3).
var v1Attrs = []Attr{
	{Name: "change", Kind: "text"},
	{Name: "initiator", Kind: "text"},
	{Name: "kind", Kind: "text"},
	{Name: "name", Kind: "text", Optional: true},
	{Name: "occurred_at", Kind: "timestamp"},
	{Name: "resource_id", Kind: "text"},
	{Name: "scope", Kind: "text"},
}

// version — выпущенная версия шаблона тела.
type version struct {
	fp    string
	tmpl  *template.Template
	attrs []Attr
}

// fingerprint — отпечаток версии n: текст шаблона и постоянные, которые он
// подставляет из других пакетов (форма имени, алфавит и приставка id, ключ
// и тип строки сигнала, класс). Смена любой из них — новая версия.
func fingerprint(n int, text string) string {
	h := sha256.New()
	for _, part := range []string{text, nameform.Form, crockford, ids.PrefixNotificationHyphen,
		spec.FeedSignalKey, spec.FeedSignalObjectType, string(spec.ClassNotice), namePayloadKey} {
		h.Write([]byte(part))
		h.Write([]byte{0})
	}
	return "v" + strconv.Itoa(n) + ":sha256:" + hex.EncodeToString(h.Sum(nil))
}

func mustVersion(n int, text string, attrs []Attr) version {
	return version{
		fp:    fingerprint(n, text),
		tmpl:  template.Must(template.New("v" + strconv.Itoa(n)).Option("missingkey=error").Parse(text)),
		attrs: attrs,
	}
}

var (
	v1       = mustVersion(1, v1Text, v1Attrs)
	released = map[string]version{v1.fp: v1}
)

// Current — отпечаток действующей версии шаблона: её пишет notifygen init.
func Current() string { return v1.fp }

// Released — отпечатки выпущенных версий по возрастанию номера.
func Released() []string { return []string{v1.fp} }

// outboxInsert — начало вставки строки ленты службы svc. Имя таблицы ленты
// производит только tablename (ведомость гейта AuditFeedTableWrites).
func outboxInsert(svc string) string {
	return fmt.Sprintf("INSERT INTO %s", tablename.Of(svc, tablename.Outbox))
}

// bodyData — подстановки шаблона тела.
type bodyData struct {
	Version, Service, Module, SignalObject, Table, SignalChange string
	C                                                           Columns
	SchemaRev                                                   int
	TTLSeconds                                                  int64
	Function, Template, Class, IDPrefix, Alphabet, NameKey      string
	NameForm, SignalKey, InsertInto, KindRows, ChangeRows       string
}

// renderBody — определение функции версии b.Version на входах b.Inputs.
func renderBody(b Body) (string, error) {
	v, ok := released[b.Version]
	if !ok {
		return "", fmt.Errorf("%w: %s", ErrVersion, b.Version)
	}
	in := b.Inputs
	if err := in.Validate(); err != nil {
		return "", err
	}
	sig, err := spec.FeedSignal(in.Module)
	if err != nil {
		return "", fmt.Errorf("%w: %w", ErrInputs, err)
	}
	kinds := make([]string, len(in.Kinds))
	for i, k := range in.Kinds {
		kinds[i] = fmt.Sprintf("      ('%s', '%s', '%s')", k.Name, k.NameForm, k.Scope)
	}
	changes := make([]string, len(in.Changes))
	for i, c := range in.Changes {
		changes[i] = fmt.Sprintf("      ('%s', '%s')", c.Word, c.Change)
	}
	var out bytes.Buffer
	err = v.tmpl.Execute(&out, bodyData{
		Version: b.Version, Service: in.Service, Module: in.Module, SignalObject: sig.Object, Table: in.Table,
		SignalChange: in.SignalChange, C: in.Columns, SchemaRev: in.SchemaRev, TTLSeconds: int64(in.TTL / time.Second),
		Function: FunctionName, Template: TemplateName, Class: string(spec.ClassNotice),
		IDPrefix: ids.PrefixNotificationHyphen + "-", Alphabet: crockford, NameKey: namePayloadKey,
		NameForm: nameform.Form, SignalKey: sig.Key, InsertInto: outboxInsert(in.Service),
		KindRows: strings.Join(kinds, ",\n"), ChangeRows: strings.Join(changes, ",\n"),
	})
	if err != nil {
		return "", fmt.Errorf("resourceevent: шаблон %s: %w", b.Version, err)
	}
	return out.String(), nil
}

// Render — миграция функции f: Up — определение f.Up и, у первой миграции
// журнала, триггер; Down — снятие триггера и функции либо прежнее
// определение f.Prev. Триггер у CREATE OR REPLACE не пересоздаётся: он связан
// с объектом функции, а замена меняет только тело.
func Render(f File) (string, error) {
	up, err := renderBody(f.Up)
	if err != nil {
		return "", err
	}
	in := f.Up.Inputs
	var b strings.Builder
	b.WriteString(fileHeader)
	if f.Prev == nil {
		fmt.Fprintf(&b, "-- notifygen resource-event: функция и триггер журнала %s\n\n", in.Table)
	} else {
		if f.Prev.Inputs.Table != in.Table || f.Prev.Inputs.Columns.Kind != in.Columns.Kind {
			return "", fmt.Errorf("%w: новое определение на журнале %s (колонка вида %s), прежнее — %s (%s): триггер этим правилом не пересоздаётся",
				ErrInputs, in.Table, in.Columns.Kind, f.Prev.Inputs.Table, f.Prev.Inputs.Columns.Kind)
		}
		fmt.Fprintf(&b, "-- notifygen resource-event: новое определение функции журнала %s\n\n", in.Table)
	}
	b.WriteString("-- +goose Up\n")
	b.WriteString(up)
	if f.Prev == nil {
		fmt.Fprintf(&b, "CREATE TRIGGER %[1]s\n  AFTER INSERT ON %[2]s\n  FOR EACH ROW WHEN (NEW.%[3]s <> '%[4]s')\n  EXECUTE FUNCTION %[1]s();\n",
			FunctionName, in.Table, in.Columns.Kind, spec.FeedSignalKey)
	}
	b.WriteString("\n-- +goose Down\n")
	if f.Prev == nil {
		fmt.Fprintf(&b, "DROP TRIGGER %[1]s ON %[2]s;\nDROP FUNCTION %[1]s();\n", FunctionName, in.Table)
		return b.String(), nil
	}
	prev, err := renderBody(*f.Prev)
	if err != nil {
		return "", fmt.Errorf("прежнее определение: %w", err)
	}
	b.WriteString(prev)
	return b.String(), nil
}
