// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: Apache-2.0

// Package schema строит DDL ленты извещений у источника (§6, З6). Миграцию
// пишет notifygen init; генератор держит побайтовое содержимое каждой
// выпущенной версии (её даёт эта функция) и сверяет с ним файлы дерева (D04).
//
// Миграция несёт только таблицы, индексы и ограничения: ни функции, ни
// процедуры, ни триггера (УК87 (а)).
package schema

import (
	"fmt"
	"sort"
	"strings"

	"github.com/PRO-Robotech/corelib/notify/feed/internal/tablename"
)

// Version — версия схемы ленты.
type Version int

// Выпущенные версии.
const (
	// V1 — схема NTF-1.
	V1 Version = 1
)

// Versions — выпущенные версии по возрастанию.
func Versions() []Version { return []Version{V1} }

// Current — действующая версия.
func Current() Version { return V1 }

// States — закрытый перечень состояний строки ленты (З6): pending либо вид
// терминального исхода.
func States() []string {
	return []string{"pending", "sent", "recipient_rejected", "denied", "invalid", "dropped", "expired"}
}

// OutcomePairs — ЕДИНСТВЕННАЯ таблица «состояние × причина» (Р11, словарь
// контракта corelib.notify). CHECK outcome_pair строится из неё, сервер ленты
// судит по ней Ack. Пустой перечень — у состояния причины нет.
func OutcomePairs() map[string][]string {
	return map[string][]string{
		"pending":            nil,
		"sent":               nil,
		"recipient_rejected": nil,
		"denied":             {"revoked"},
		"invalid": {"attrs_invalid", "class_mismatch", "recipient_invalid", "class_not_allowed",
			"recipient_form_not_allowed", "sealed_mismatch", "key_unavailable"},
		"dropped": {"recipient_net"},
		"expired": {"platform_unavailable", "grant_skew", "template_skew", "recipient_net", "unclaimed", "no_ack"},
	}
}

// DDL — операторы версии v для службы svc: up и down.
func DDL(svc string, v Version) (up, down string, err error) {
	if err := tablename.Valid(svc); err != nil {
		return "", "", fmt.Errorf("schema: %w", err)
	}
	switch v {
	case V1:
		return v1Up(svc), v1Down(svc), nil
	}
	return "", "", fmt.Errorf("schema: версия %d не выпущена", int(v))
}

// HeaderPrefix — начало строки заголовка миграции ленты: по ней notifygen
// -check узнаёт службу и версию применённого файла и сверяет его побайтово с
// выпущенным содержимым (D04).
const HeaderPrefix = "-- notifygen feed schema:"

// Migration — файл миграции goose версии v для службы svc.
func Migration(svc string, v Version) (string, error) {
	up, down, err := DDL(svc, v)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("-- Code generated by notifygen init; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "%s service=%s version=%d\n\n", HeaderPrefix, svc, int(v))
	b.WriteString("-- +goose Up\n")
	b.WriteString(up)
	b.WriteString("\n-- +goose Down\n")
	b.WriteString(down)
	return b.String(), nil
}

func quoteList(words []string) string {
	q := make([]string, len(words))
	for i, w := range words {
		q[i] = "'" + w + "'"
	}
	return strings.Join(q, ", ")
}

// outcomePairCheck — выражение CHECK outcome_pair: у состояния без причин
// причина NULL, у прочих — из своего перечня.
func outcomePairCheck() string {
	pairs := OutcomePairs()
	states := make([]string, 0, len(pairs))
	for s := range pairs {
		states = append(states, s)
	}
	sort.Strings(states)
	var parts []string
	for _, s := range states {
		if len(pairs[s]) == 0 {
			parts = append(parts, fmt.Sprintf("(state = '%s' AND outcome_reason IS NULL)", s))
			continue
		}
		parts = append(parts, fmt.Sprintf("(state = '%s' AND outcome_reason IN (%s))", s, quoteList(pairs[s])))
	}
	return strings.Join(parts, "\n    OR ")
}

// v1Up — результат tablename.Of только аргументом Sprintf, повтор вида —
// %[n]s (ведомость писателей таблиц ленты, УК90, УК92).
func v1Up(svc string) string {
	return fmt.Sprintf(`CREATE TABLE %[1]s (
  id                text        PRIMARY KEY,
  template          text        NOT NULL,
  schema_rev        integer     NOT NULL CHECK (schema_rev >= 1),
  class             text        NOT NULL CHECK (class IN ('security', 'notice')),
  recipient_address text        NOT NULL,
  attrs             jsonb       NOT NULL,
  secret_attrs      bytea,
  state             text        NOT NULL CHECK (state IN (%[4]s)),
  outcome_reason    text,
  outcome_at        timestamptz,
  recorded_kind     text,
  recorded_reason   text,
  outcome_token     uuid,
  lease_token       uuid,
  lease_until       timestamptz,
  first_claimed_at  timestamptz,
  last_defer_reason text,
  not_before        timestamptz CHECK (not_before IS NULL OR isfinite(not_before)),
  enqueued_at       timestamptz NOT NULL DEFAULT now(),
  expires_at        timestamptz NOT NULL,
  CONSTRAINT closed_carries_no_secret CHECK (state = 'pending' OR secret_attrs IS NULL),
  CONSTRAINT outcome_matches_state CHECK ((state <> 'pending') = (outcome_at IS NOT NULL)),
  CONSTRAINT outcome_pair CHECK (
    %[5]s)
);
CREATE INDEX %[6]s ON %[1]s (class, enqueued_at, id) WHERE state = 'pending';
CREATE INDEX %[7]s ON %[1]s (outcome_at) WHERE state <> 'pending';
CREATE TABLE %[2]s (
  template       text        NOT NULL,
  scope          text        NOT NULL,
  window_seconds integer     NOT NULL CHECK (window_seconds > 0),
  key            text        NOT NULL,
  window_start   timestamptz NOT NULL,
  count          integer     NOT NULL CHECK (count >= 0),
  PRIMARY KEY (template, scope, window_seconds, key, window_start)
);
CREATE TABLE %[3]s (
  notification_id text        NOT NULL REFERENCES %[1]s (id) ON DELETE CASCADE,
  template        text        NOT NULL,
  scope           text        NOT NULL,
  window_seconds  integer     NOT NULL CHECK (window_seconds > 0),
  key             text        NOT NULL,
  window_start    timestamptz NOT NULL,
  PRIMARY KEY (notification_id, scope, window_seconds)
);
`, tablename.Of(svc, tablename.Outbox), tablename.Of(svc, tablename.Window), tablename.Of(svc, tablename.Contrib),
		quoteList(States()), outcomePairCheck(),
		tablename.Index(svc, tablename.Outbox, tablename.Pending), tablename.Index(svc, tablename.Outbox, tablename.Closed))
}

func v1Down(svc string) string {
	return fmt.Sprintf("DROP TABLE %s;\nDROP TABLE %s;\nDROP TABLE %s;\n",
		tablename.Of(svc, tablename.Contrib), tablename.Of(svc, tablename.Window), tablename.Of(svc, tablename.Outbox))
}
